### ISSUE TITLE
magic-admin build的时候报一堆Unable to compile TypeScript

### ISSUE THREAD

**Issue by lecykx** [Tencent/tmagic-editor#100]
进magic-admin的时候执行setup.sh即web build的时候报一堆Unable to compile TypeScript问题

**Comment by lecykx** [comment]
自己解决了，涉及sequelize相关版本即可
卸载相关包后再执行安装
npm install --save-dev @types/node @types/validator
npm install sequelize reflect-metadata sequelize-typescript

对应的版本为，即可解决
"sequelize": "^6.20.1",
"sequelize-typescript": "^2.1.3"

"@types/node": "^17.0.38",
"@types/validator": "^13.7.2",

**Comment by khuntoriia** [comment]
请pull最新的代码试试
