### ISSUE TITLE
MagicEditor import error

### ISSUE THREAD

**Issue by yoohoolai** [Tencent/tmagic-editor#105]
import MagicEditor from "@tmagic/editor";

Uncaught Error: Secure random number generation is not supported by this browser.
Use Chrome, Firefox or Internet Explorer 11
    at oldBrowser (browser.js:12:9)
    at generateUID (index.js:38:17)
    at node_modules/_serialize-javascript@6.0.0@serialize-javascript/index.js (index.js:13:27)
    at __require2 (chunk-JZING22Y.js?v=cd9a69f8:47:50)
    at dep:@tmagic_editor:1:1

**Comment by jia000** [comment]
vue3 does not  not support ie11

**Comment by yoohoolai** [comment]
测试用的是chrome浏览器

**Comment by jia000** [comment]
请提供详细的信息
浏览器版本，node版本，webpack或者vite版本，babel版本等

**Comment by yoohoolai** [comment]
1、Chrome 已是最新版本
版本 102.0.5005.63（正式版本） （64 位）

**Comment by yoohoolai** [comment]
Chrome 版本 102.0.5005.63（正式版本） （64 位）、node v16.12.0、vite 2.9.9、babel 7.18.2

**Comment by yoohoolai** [comment]
vite.config.js配置信息：
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import legacy from '@vitejs/plugin-legacy';
import vueJsx from '@vitejs/plugin-vue-jsx';
export default defineConfig({
  define: {
	 global:{} 
  },
  plugins: [
    vue(),
    vueJsx(),
    legacy({
      targets: ['defaults', 'not IE 11'],
	  additionalLegacyPolyfills:['regenerator-runtime/runtime']
    })
  ],
  build: {
    sourcemap: true,
    minify: false,

    rollupOptions: {
      input: {
        page: './page.html',
        playground: './playground.html',
        components: './src/comp-entry.ts',
        config: './src/config-entry.ts',
        value: './src/value-entry.ts',
      },
      output: {
        entryFileNames: 'assets/[name].js',
      },
    },
  }
})

**Comment by jia000** [comment]
additionalLegacyPolyfills:['regenerator-runtime/runtime']

**Comment by yoohoolai** [comment]
去掉一样不行

**Comment by jia000** [comment]
上面贴出来的vite.config应该是runtime的配置，MagicEditor 应该是在另一个项目中使用的，是不是弄错了
