### ISSUE TITLE
发布后无法访问项目页面，vendor.3f0d9265.js找不到

### ISSUE THREAD

**Issue by zhuichen** [Tencent/tmagic-editor#106]
在runtime vue3模块中打包完成后，并没有vendorxxx.js这个文件，不知道是不是这个文件导致无法访问
![image](https://user-images.githubusercontent.com/13943847/172284617-70c9fd45-6fe2-490d-9925-3a69037c61ef.png)

**Comment by Zian502** [comment]
我这边打包出来的跟你不一样。
![image](https://user-images.githubusercontent.com/26033663/172593012-7a4901c0-b014-4aed-8bcc-c3453087eb56.png)

**Comment by jia000** [comment]
请详细描述清楚问题
