### ISSUE TITLE
【疑问】有计划支持多端发布吗？即一套组件即可以打包发布H5页面也能发布为小程序页面

### ISSUE THREAD

**Issue by XuQianru** [Tencent/tmagic-editor#112]
目前项目中需要用到多端发布能力，如果近期没有计划支持，可以简单介绍下实现思路吗？

**Comment by jia000** [comment]
两种方案：1.利用vue或者react的跨端能力；2、开发小程序组件，然后通过解析编辑器产出的DSL，生成一个小程序页面的源码

**Comment by jia000** [comment]
对于用什么跨端框架并没有什么要求，如果有现存的vue组件可以看看https://github.com/Tencent/kbone，如果是重头开始的Tora、uni-app应该更合适

**Comment by XuQianru** [comment]
感谢解答~
