### ISSUE TITLE
管理端编辑器页面点击保存，服务端 sql 报错

### ISSUE THREAD

**Issue by Zian502** [Tencent/tmagic-editor#117]
操作界面：
![image](https://user-images.githubusercontent.com/26033663/172974368-0464c571-d1fd-4a47-94f2-a86b55b6a3f4.png)

报错信息：
![image](https://user-images.githubusercontent.com/26033663/172974313-5913db30-f075-40c0-ace0-69b4a9561ae0.png)

**Comment by khuntoriia** [comment]
请pull最新代码试试
