### ISSUE TITLE
position: 'fixed'初始化配置不生效问题

### ISSUE THREAD

**Issue by yoohoolai** [Tencent/tmagic-editor#136]
![image](https://user-images.githubusercontent.com/17917474/173832568-4c0186fd-f8b2-4bff-84b7-c777fa5e65e5.png)
请问右边的样式区里的固定定位如何赋初始值，组件中的initValue.ts赋style: {position: 'fixed',}不生效

**Comment by jia000** [comment]
使用的是最新版本吗，@tmagic/editor的npm版本是多少
