### ISSUE TITLE
可以考虑插件和组件支持按端过滤

### ISSUE THREAD

**Issue by sbiweeq** [Tencent/tmagic-editor#146]
组件列表,展示根据当前编辑的模式进行加载相应组件,避免有些定制化组件在pc或者mobile下不支持的问题

比如,组件在pc模式下的显示控制,
专属于pc模式的组件,
专属于mobile模式下的组件

**Comment by jia000** [comment]
这个需要自行实现，componentGroupList跟根据页面类型变化就可以了
