### ISSUE TITLE
app下不能添加组件

### ISSUE THREAD

**Issue by CarryKiana** [Tencent/tmagic-editor#151]
无论是根据hellowworld文档写出来的代码，还是复制教程代码（https://github.com/jia000/tmagic-tutorial）运行，点击组件的时候都报以下错误：
Uncaught (in promise) Error: app下不能添加组件
    at Editor$1.add (editor.ts:297:13)
    at async doAction (BaseService.ts:53:28)
add @ editor.ts:297

**Comment by jia000** [comment]
直接运行tmagic-turorial也报这个错误？

**Comment by isensen** [comment]
@CarryKiana 你是按照教程代码来的是吧?安装后的默认版本我记得是rc6, 你把版本换成rc13试一下

**Comment by CarryKiana** [comment]
> @CarryKiana 你是按照教程代码来的是吧?安装后的默认版本我记得是rc6, 你把版本换成rc13试一下

好的，我试一下

**Comment by CarryKiana** [comment]
> 直接运行tmagic-turorial也报这个错误？

没运行过，我试试

**Comment by CarryKiana** [comment]
> @CarryKiana 你是按照教程代码来的是吧?安装后的默认版本我记得是rc6, 你把版本换成rc13试一下

确认是版本的问题，更换后添加组件没有报错

**Comment by CarryKiana** [comment]
> 直接运行tmagic-turorial也报这个错误？

确认是版本的问题，更换后添加组件没有报错
