### ISSUE TITLE
有时刷新会stage空白

### ISSUE THREAD

**Issue by isensen** [Tencent/tmagic-editor#160]
执行的测试runtime:  vue3 runtime

一直刷新页面,有时runtime下的vue3的playground App.vue的onMounted 会早于 StageRender里的 loadHandler执行,造成onMounted 时, window还未挂载magic, 导致不会执行onRuntimeReady, 导致页面有时空白.

另问一下: 为什么 runtime vue3里的playground里的App.vue ,要使用:
```
const componentUrl = '/tmagic-editor/playground/runtime/vue3/assets/components.js';
import(componentUrl)
```
为什么不像page的 app.vue里一直直接使用
```
import entry from '../comp-entry';
const { components, plugins } = entry;
```
是有其它原因吗?

我把这种加载方式改掉,  然后onMounted 里添加
```
window.addEventListener('message', ({ data }) => {
        if (!data.tmagicRuntimeReady) {
          return;
        }
        window.magic?.onRuntimeReady({
          getApp() {
            return app;
          },
...
```
就可以解决这个有时白屏的现象, 但是没有发pr, 不知道原来的写法是不是有别的用途

**Comment by jia000** [comment]
const componentUrl = '/tmagic-editor/playground/runtime/vue3/assets/components.js';
import(componentUrl)

这个写法的初衷是想让playground与page公用同一份组件产物，目前看来并没什么优势，已经改掉了

window.addEventListener('message') 
这种方式是正确的写法，这个是后面才支持的

**Comment by isensen** [comment]
@jia000 了解了
