### ISSUE TITLE
咨询-请问后续有考虑支持一些基本的组件吗

### ISSUE THREAD

**Issue by wrr008123** [Tencent/tmagic-editor#173]
如题

**Comment by jia000** [comment]
是需要什么组件？

**Comment by wrr008123** [comment]
主要是目前tmagic-playground所提供的组件都是属于demo级别，十分简单，而我想要自己开发一些交互复杂的组件（并非demo级别的），但是由于能力有限，所以想要通过学习你们写的基本组件的方式去模仿

所以希望能提供一组（或几个）真正在上线的时候使用到的组件（最好能提供一两个复杂度较高的组件）能够用于学习

非伸手党，本人是做后端开发的，并不是很懂前端，所以才产生当前需求，望理解

**Comment by jia000** [comment]
抱歉，组件都是要依据业务需求来了，现在开源的组件有很多，可以封装一下再集成到tmagic中来。对于tmagic，组件是否复杂并不关心，它只是负责渲染出来，还有提供一下拖拽交互与属性配置

**Comment by wrr008123** [comment]
好的，谢谢
