### ISSUE TITLE
https://tencent.github.io/tmagic-editor/playground/index.html

### ISSUE THREAD

**Issue by ibmsoft** [Tencent/tmagic-editor#185]
体验版
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/26042/179221585-f8615c86-5f04-4307-a193-dc4315630032.png">

**Comment by jia000** [comment]
https://github.com/Tencent/tmagic-editor/commit/a4abf5feea39300d22757003e48145065ab7672c
