### ISSUE TITLE
处于蒙层里面自定义组件的方法无法被自定义事件触发

### ISSUE THREAD

**Issue by kevnwei** [Tencent/tmagic-editor#186]
![screenshot-20220718-115420](https://user-images.githubusercontent.com/3196263/179443014-5d1fa23f-1c56-4f34-8957-50ef6106d48a.png)

![screenshot-20220718-120410](https://user-images.githubusercontent.com/3196263/179443734-2ae557de-030c-419c-9a04-06ae723c0017.png)

自定义事件“抽奖成功”(app.emit('draw:success', node)) --> 触发蒙层弹窗方法“打开蒙层”（成功） --> 再触发“中奖弹窗”组件自定义方法“弹窗警告”（失败）

原因调试定位到：
package/core/src/App.ts里面的bindEvents()方法判断响应方法的地方，204行：
if (typeof toNode.instance?.[methodName] === 'function') {

这里的toNode.instance 为 undefined，所以无法调用对应的方法：toNode.instance?.[methodName]

但是如果修改一下bindEvents() 里面代码，把上面的判断条件放到setTimeout里面调用toNode.instance?.[methodName]可以调用到。

现在问题是：
能不能在不修改package/core里面的代码情况下，实现自定义组件的自定义事件触发组件方法？

**Comment by jia000** [comment]
弹窗警告，这个是一个vue组件吗，是在什么时机下created？

**Comment by jia000** [comment]
修改core的方法，直接改原型链或者或defineProperty，但是不建议这么做，还是看看是什么问题，完善一下core好点

**Comment by kevnwei** [comment]
> 

就是上面“中奖弹窗”的一个openAlert方法，调试用的方法。

<script lang="ts">
import { defineComponent, PropType, } from 'vue';
import Core from '@tmagic/core';
import { MAwardpopup } from '../types';
import useApp from '../useApp';

export default defineComponent({
  name: 'magic-ui-awardpopup',
  props: {
    config: {
      type: Object as PropType<MAwardpopup>,
      default: () => ({}),
    },

    model: {
      type: Object,
      default: () => ({}),
    },
  },
  setup(props) {
    const app: Core | undefined = useApp(props);
    const node = app?.page?.getNode(props.config.id);
    const openAlert = () => {
      alert(333);
    };

    return {
      openAlert,
    };
  },
});
</script>

**Comment by kevnwei** [comment]
原因就是 被调用方法所属的组件 事件触发的时候还没创建好。
如本case的事件，同时触发两个动作，1: 蒙层弹出，2: 蒙层里面的“中奖弹窗”组件（此时还没创建好，instance为undefined），导致调用instance里面的方法失败。

**Comment by jia000** [comment]
明白了，这里我改一下core，需要维护一个事件调用的队列，如果instance还没有把method放入队列，等instance created在去队列里拿method调用

**Comment by jia000** [comment]
https://github.com/Tencent/tmagic-editor/commit/1750467d5b0407bba4c388716cd71298c49de8e6

**Comment by jia000** [comment]
v1.1.0-beta.3
