### ISSUE TITLE
monaco-editor依赖是否有必要？

### ISSUE THREAD

**Issue by kevnwei** [Tencent/tmagic-editor#189]
代码编辑功能使用频率本来不高（或者只需一个简单的json/js编辑器），build打包出来的文件大小，monaco-editor占比却非常高，包含各种无用语言的scripts文件。

**Comment by jia000** [comment]
只要不渲染，是不会去加载monaco-editor相关的的js资源的

**Comment by jia000** [comment]
代码编辑的频率高不高取决于业务，如果业务到后期是会有需要配置函数这种需求的，会需要在编辑器中写代码

**Comment by kevnwei** [comment]
但是貌似还是把代码打包到vendor里面了（还是我打包的姿势不对？），并且浏览器要一起下载，不管有没有渲染，页面加载比较慢影响用户体验。另外配置函数这种需求，一般都是简单的逻辑，感觉暂时不需要monaco-editor这么重量级的产品～，而且她还包含各种语言支持。

**Comment by jia000** [comment]
是会把monaco-editor的基础代码打进去，语言支持相关的代码是用到时才加载的

**Comment by jia000** [comment]
后续改成整个monaco-editor动态加载，不需要可以不加载的模式

**Comment by jia000** [comment]
不支持了
