### ISSUE TITLE
./src/App.vue?vue&type=template&id=7ba5bd90&ts=true报错

### ISSUE THREAD

**Issue by KuangNan** [Tencent/tmagic-editor#190]
我使用官网上的教程https://tencent.github.io/tmagic-editor/docs/tutorial/hello-world.html#%E5%88%9B%E5%BB%BA%E9%A1%B9%E7%9B%AE
然后我的项目报错
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/71868336/179745289-316b87d3-4a1d-48b7-8b3d-6342c71cabb7.png">

**Comment by jia000** [comment]
https://github.com/jia000/tmagic-tutorial/tree/master/course1/hello-world

**Comment by KuangNan** [comment]
是的

**Comment by jia000** [comment]
提供一下操作系统、node 版本

**Comment by KuangNan** [comment]
Darwin：arm64
node：v18.5.0

**Comment by jia000** [comment]
使用node16
