### ISSUE TITLE
最新的 master 执行 npm run pg 修改 editor 后出现错误

### ISSUE THREAD

**Issue by nikewu** [Tencent/tmagic-editor#191]
最新的 master 执行 npm run pg 然后修改，然后出现报错
![image](https://user-images.githubusercontent.com/12083690/179753577-39c3136d-af6d-436b-99d3-d21bb55b2618.png)
![image](https://user-images.githubusercontent.com/12083690/179753827-596129f7-47c0-4fd1-b576-deac1c9ad6dd.png)

请问这个是版本问题吗 ？

**Comment by jia000** [comment]
修改了editor.vue里的什么代码？

**Comment by nikewu** [comment]
![image](https://user-images.githubusercontent.com/12083690/179921216-6a902834-4631-401c-93ab-9edadc706a61.png)
比如这个名字，然后保存后触发 hmr 就会有那个错误 @jia000

**Comment by nikewu** [comment]
如果我修改 playground 里  main.ts 会触发页面级别的 reload 就不会有这个错误

**Comment by jia000** [comment]
这种情况应该是，刷新一下页面就好了吧？

**Comment by nikewu** [comment]
但是如果我在改 playground 的代码的话，基本上每次改一下都会出这个错，然后我再重新刷整个页面

**Comment by nikewu** [comment]
大佬你那边能复现吗 ？ 我看着好像是 vite  hmr 和 iframe 里面的事件状态有冲突

**Comment by jia000** [comment]
会有这个问题
