### ISSUE TITLE
多选后操作问题

### ISSUE THREAD

**Issue by wrr008123** [Tencent/tmagic-editor#199]
多选后，设置水平居中，或者是删除，只会删除第一个组件

个人认为多选后行为应该一致

![多选不合理](https://user-images.githubusercontent.com/34823541/180634906-80d7ce4d-0126-44de-b3d9-93b4d45cbed5.gif)

**Comment by khuntoriia** [comment]
反馈已收到，请关注后续PR更新

**Comment by khuntoriia** [comment]
https://github.com/Tencent/tmagic-editor/pull/217
