### ISSUE TITLE
按照readme总是出错，依赖无法解决。各种报错。

### ISSUE THREAD

**Issue by yzx1208** [Tencent/tmagic-editor#207]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: vue-jest@3.0.7
npm ERR! Found: vue@3.2.33
npm ERR! node_modules/vue
npm ERR! vue@"^3.2.26" from the root project
npm ERR! peer vue@"^3.2.0" from @element-plus/icons-vue@2.0.6
npm ERR! node_modules/@element-plus/icons-vue
npm ERR! @element-plus/icons-vue@"^2.0.6" from element-plus@2.2.10
npm ERR! node_modules/element-plus
npm ERR! element-plus@"^2.2.6" from the root project
npm ERR! 2 more (@tmagic/editor, @tmagic/form)
npm ERR! 12 more (@tmagic/editor, @tmagic/form, @vue/babel-preset-app, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^2.x" from vue-jest@3.0.7
npm ERR! node_modules/vue-jest
npm ERR! dev vue-jest@"^3.0.7" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: vue@2.7.8
npm ERR! node_modules/vue
npm ERR! peer vue@"^2.x" from vue-jest@3.0.7
npm ERR! node_modules/vue-jest
npm ERR! dev vue-jest@"^3.0.7" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2022-07-27T03_15_12_697Z-debug-0.log

**Comment by jia000** [comment]
是用pnpm吗

**Comment by yzx1208** [comment]
> 是用pnpm吗
我使用的环境是：
1.离线
2.centos7
3.node 16.16
4.直接在magic-admin目录下执行setup.sh
结果是失败，已经装了两天了还是没法解决，是不是有额外的依赖需要联网？

**Comment by jia000** [comment]
不要执行setup.sh
cd web
npm i
npm run serve

cd server
npm i
npm run dev
