### ISSUE TITLE
Uncaught SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by Wbiokr** [Tencent/tmagic-editor#219]
magic-admin安裝依赖之后，npm run  serve，浏览器抛异常Uncaught SyntaxError: Unexpected token .

**Comment by jia000** [comment]
请提供详细点的信息

**Comment by LdPz-ROOM** [comment]
Uncaught SyntaxError: Unexpected token '<' (at index.umd.js:1:1)

加载脚本文件
