### ISSUE TITLE
自定义组件如何打包？

### ISSUE THREAD

**Issue by 9aoyang** [Tencent/tmagic-editor#248]
[如何开发一个组件](https://tencent.github.io/tmagic-editor/docs/component/introduction.html)

这篇文档里提到的打包脚本，源码里已经不存在了， 不知道现在要如何打包自定义组件？（顺便问下文档什么时候能更新到 vite 版本）

**Comment by jia000** [comment]
打包脚本已经移到@tmagic/cli中了

**Comment by jia000** [comment]
/Users/gaoyang/Documents/gis-component/runtime/vue3/components这个目录下要export default {  type: Component， ... } 这种形式的，可以参照ui里的写法
