### ISSUE TITLE
有没有考虑过事件驱动改成数据驱动的形式呀，用来做数据大屏

### ISSUE THREAD

**Issue by ututuut** [Tencent/tmagic-editor#250]
有没有考虑过事件驱动改成数据驱动的形式呀，用来做数据大屏

**Comment by jia000** [comment]
事件驱动还是数据驱动跟做数据大屏有什么影响吗？对数据大屏并没有了解过其特殊性

**Comment by ututuut** [comment]
![image](https://user-images.githubusercontent.com/19516729/184091425-6c471f55-66f8-4a11-923b-4a60d870bcad.png)
像这样子，组件1修改时间这一列的数据，组件2折线图组件可以立马将数据渲染到UI上

**Comment by ututuut** [comment]
普通用户可以大量的使用excel里面的公式，可以不在使用js脚本了。我们这些开发者只需要维护组件好了

**Comment by jia000** [comment]
这个是组件间的关联关系，应该是组件内部需要去处理的事情，或者可以使用插件去做，编辑器只是负责组件的增删改查
