### ISSUE TITLE
第三方组件在预览时应该如何注册

### ISSUE THREAD

**Issue by 9aoyang** [Tencent/tmagic-editor#253]
开发中用到了第三方的地图组件，[代码地址](https://github.com/9aoyang/gis-component/blob/main/runtime/vue3/components/gis/src/index.vue)

在 runtime 安装相应依赖后可以正常显示
![image](https://user-images.githubusercontent.com/17688032/183873182-b434c711-8917-4826-99fc-e8d1b9da21ea.png)

但是在预览的 `iframe` 中就不行了
![image](https://user-images.githubusercontent.com/17688032/183873240-a293db81-cd3e-4613-b9f4-9de3b36cc42e.png)

想了解现在有相应的解决方案吗？

**Comment by jia000** [comment]
https://github.com/9aoyang/gis-component/pull/1
