### ISSUE TITLE
添加自定义组件后，再添加组件会提示组件不存在

### ISSUE THREAD

**Issue by 9aoyang** [Tencent/tmagic-editor#259]
如图，当添加自定义组件后，不点击其他区域，直接继续添加组件（ui组件和自定义组件皆可），都会报错并且无法添加组件。

![image](https://user-images.githubusercontent.com/17688032/184093982-003607d0-2c62-4b7b-9d5f-d78081932ede.png)

**Comment by jia000** [comment]
请提供更多信息

**Comment by 9aoyang** [comment]
[项目地址](https://github.com/9aoyang/gis-component)
运行 vue3 的 runtime，连续点击添加自定义组件即可复现

**Comment by jia000** [comment]
initValues.ts中不要加items:[],加了就表示是容器，选中的时候添加的组件会加到这个容量里
