### ISSUE TITLE
如何更新magic-admin/server/static/vue3/entry下的内容

### ISSUE THREAD

**Issue by toadprince** [Tencent/tmagic-editor#287]
如题，magic-admin/server/static/vue3/下有两个文件夹，一个是entry，一个是runtime，runtime的更新可以从playground/dist下复制过去的，entry的内容如何更新呢？开发环境下的页面渲染用到了这个文件夹

**Comment by jia000** [comment]
在runtime/vue3下执行npm run build:admin就会在dist目录生成runtime跟entry两个文件夹，把这两个文件复制过去就行了

**Comment by toadprince** [comment]
在runtime/vue3下执行build:admin确实可以得到想要的文件，不过放到magic-admin/server/static/vue3/下有问题，点击左侧组件时报错：Error: 未找到父节点。
为此，我还专门全新clone了全新源码，源码中magic-admin/server/static/vue3/原本就有的文件没问题，通过build:admin得到的文件放过去就有问题。

**Comment by jia000** [comment]
@tmagic/editor 更新到1.1.0-beta.10
