### ISSUE TITLE
组件注册 name 一定要是 magic-ui-XX？

### ISSUE THREAD

**Issue by 9aoyang** [Tencent/tmagic-editor#291]
我尝试了不使用 `magic-ui-xx` 的形式自定义组件，发现仅仅是这个改动就会让组件无法正常使用。另外，我也尝试使用组合式 api 的方式来自定义组件，同样也无法正常渲染，不知道这是目前的组件规范还是说没考虑到？

**Comment by jia000** [comment]
magic-ui-xx，是组件规范，这点是可以做到使用方无感的，这里需要修改一下runtime
composition-api没有name，这点确实没有考虑到；

**Comment by 9aoyang** [comment]
react 组件也没有 name，但是好像组件可以正常渲染？

**Comment by jia000** [comment]
react的引用方式不一样

**Comment by ututuut** [comment]
还真的是bug，我还测试了好久，期待官方快速修复

**Comment by jia000** [comment]
请升级到1.1.0-beta.11
