### ISSUE TITLE
配置中的number类型可以做成按住鼠标左键向上拉，数值变大，向下拉数值变小这种吗。这样子开发真的很快。用adobe  xd的感受

### ISSUE THREAD

**Issue by ututuut** [Tencent/tmagic-editor#294]
像视屏这样子的

https://user-images.githubusercontent.com/19516729/185535443-19db9211-64a5-4b98-89a9-7af275d1bac0.mp4

**Comment by jia000** [comment]
可以按键盘方向键上下来调整大小，单独按上方向+1,ctrl 方向 +100, shift 方向 + 10，alt 方向 + 0.1
