### ISSUE TITLE
编辑器内"组"组件在给定高度，设置为"流式布局"，里面的内容超出"组"的高度时，无法在画布区域滑动编辑

### ISSUE THREAD

**Issue by yixiudashi** [Tencent/tmagic-editor#298]
![image](https://user-images.githubusercontent.com/12636494/185611833-cf8b394f-aaf9-4321-bbbf-1eb28bfc3286.png)

**Comment by LancerSun** [comment]
我们也遇到了这个问题，编辑区域无法在填充满了以后自动向下延展...
