### ISSUE TITLE
打包生成dist后在playground下执行server 后画布没展示内容

### ISSUE THREAD

**Issue by Carloslst** [Tencent/tmagic-editor#352]
你好，请问一下，我得到dist包后 画布没展示内容，浏览器式提示server问题 我看到是代理问题，然后我在整个项目的根目录启动项目，这个时候dist包在 preview下画布才能展示。
![1663417047624](https://user-images.githubusercontent.com/44060788/190856449-8647f7ce-e067-495a-b24f-6c0d49aab70c.png)

![1663417392785](https://user-images.githubusercontent.com/44060788/190856633-5ef0a04d-7659-434e-a2e5-9f3f04503998.png)

这里不能在playground目录下直接preview后画布出现内容吗，要是在服务器上，这个dist包会不会也出现这种情况呢

**Comment by jia000** [comment]
没看懂你的问题具体是什么
playground打包的产物，可以看https://github.com/Tencent/tmagic-editor/tree/gh-pages/playground这个是https://tencent.github.io/tmagic-editor/playground/index.html#/的资源

**Comment by Carloslst** [comment]
> 没看懂你的问题具体是什么 playground打包的产物，可以看 https://github.com/Tencent/tmagic-editor/tree/gh-pages/playground 这个是https://tencent.github.io/tmagic-editor/playground/index.html#/ 的资源

你好，上面那个截图是playground打包的产物 然后我执行了vite preview  执行了dist包，但是执行起来后画布中初始化的组件没有展示出来

**Comment by jia000** [comment]
vite preview还是会使用vite.config.ts里的配置，里面配置proxy，把runtime的index代理到了8087端口（这个是dev的时候需要）

**Comment by Carloslst** [comment]
> vite preview还是会使用vite.config.ts里的配置，里面配置proxy，把runtime的index代理到了8087端口（这个是dev的时候需要）

你好，那我这个dist包发到生产的时候，这个时候需要改动些什么吗？

**Comment by jia000** [comment]
对url 路径没有要求的话就不需要改动什么了

**Comment by Carloslst** [comment]
> 对url 路径没有要求的话就不需要改动什么了

谢谢，麻烦了
