### ISSUE TITLE
组件联动事件重复问题

### ISSUE THREAD

**Issue by isensen** [Tencent/tmagic-editor#356]
表单内的组件联动： 如两个“输入框”类型的组件 A 和  B， 都有一个本实例“值变化”时的事件，激活“下拉”组件重新加载数据。 
A 值变化时 会激活两次， 因为事件无ID标识， 会因为A和B绑定的同名事件激活两次， 看源码是default common event会自动加ID防止重复，那么这种自定义事件怎么处理？

**Comment by jia000** [comment]
能否提供一个示例？

**Comment by isensen** [comment]
> 能否提供一个示例？

自定义一个组件类型：input ，自定义它的一个事件“input:value:update"
自定义一个下拉框类型：select, 自定义它的一个方法：reload

设计页面时：
拖拽两个Input实例,拖拽一个下拉框实例。
两个input实例都添加事件，当“input:value:update"时去调用 下拉框的”reload"方法，我这遇到的是会当其中一个input发生事件时， 就会调两次reload

**Comment by jia000** [comment]
app.emit('input:value:update', node); 有没有把node传入？

**Comment by isensen** [comment]
传了

**Comment by isensen** [comment]
> app.emit('input:value:update', node); 有没有把node传入？

[bindEvent](https://github.com/Tencent/tmagic-editor/blob/ddf0fcdecce14a924ffbd3690a36fff467ca98bc/packages/core/src/App.ts#L210) 这里是在app级别直接绑的两个同名事件吧
