### ISSUE TITLE
有关组件的加载问题

### ISSUE THREAD

**Issue by cklwblove** [Tencent/tmagic-editor#366]
你好~

**问题点：**
目前组件的打包构建都是在一个 js bundle 文件里，也是同步加载的。这样会存在一个问题，当组件的数量过多，并且一些组件引用比较大的三方库（比如 echarts 等）时，就会阻塞页面的渲染，尤其是移动端页面的首屏渲染。

**解决思路和方案：**
是否可以将组件的加载改成“懒加载”模式，用于减少一些没有用到的组件加载，提升页面的渲染速度

**Comment by jia000** [comment]
.tmagic 下新增一个async-comp-entry.ts，可以使用这个来达到动态加载，runtime/vue3/page已经改成改模式，可以参考

**Comment by jia000** [comment]
playground由于加载时机问题目前无法支持动态加载模式
