### ISSUE TITLE
有没有计划添加组件显示/隐藏功能

### ISSUE THREAD

**Issue by kevnwei** [Tencent/tmagic-editor#368]
目前只有复制/删除，在看页面效果的时候显示/隐藏有时候也很有用。同时，能否在“已选组件”里面右侧直接展示功能按钮，目前只能右键弹出。
![image](https://user-images.githubusercontent.com/3196263/191455826-bdc15556-9a6a-4175-9a1e-696923319a93.png)

**Comment by jia000** [comment]
`<template #layer-node-content="{ data, node }">
      <span>{{ `${data.name} (${data.id})` }}<el-icon ><lock /></el-icon></span>
</template>`
