### ISSUE TITLE
使用官方例子进行app.use(MagicEditor)时报错

### ISSUE THREAD

**Issue by jerikchan** [Tencent/tmagic-editor#37]
![image](https://user-images.githubusercontent.com/16037149/165469497-d5efffb9-839e-45b0-b432-fa9203ceecff.png)
![image](https://user-images.githubusercontent.com/16037149/165470608-dba4db07-aa5a-4477-a5c5-dcb1a553a267.png)

报错路径是：
src/main.ts:
import MagicEditor from '@tmagic/editor';
...
app.use(MagicEditor);
->

@tmagic/editor/dist/tmagic-editor.es.js:
import serialize from 'serialize-javascript';
->

serialize-javascript/index.js:
var randomBytes = require('randombytes');
->

randombytes/browser.js:
var Buffer = require('safe-buffer').Buffer
->Uncaught TypeError: Cannot read properties of undefined (reading 'from')

报错信息：

@tmagic_editor.js?v=c6492491:707 Uncaught TypeError: Cannot read properties of undefined (reading 'from')

Uncaught TypeError: Cannot read properties of undefined (reading 'from')
    at node_modules/safe-buffer/index.js (@tmagic_editor.js?v=c6492491:707:16)
    at __require2 (chunk-TMRFOBSY.js?v=9ed9471b:47:50)
    at node_modules/randombytes/browser.js (@tmagic_editor.js?v=c6492491:764:18)
    at __require2 (chunk-TMRFOBSY.js?v=9ed9471b:47:50)
    at node_modules/serialize-javascript/index.js (@tmagic_editor.js?v=c6492491:798:23)
    at __require2 (chunk-TMRFOBSY.js?v=9ed9471b:47:50)
    at @tmagic_editor.js?v=c6492491:2893:43

**Comment by jia000** [comment]
创建polyfills.ts
内容如下
if (typeof (window as any).global === 'undefined') {
  (window as any).global = window;
}

在mait.ts最开头的地方imprt ./polyfills.ts;
试试看

**Comment by qwertyyb** [comment]
@jerikchan 有没有试过重新安装依赖npm run reinstall? 运行的是官方的playground吗？node, npm版本是多少？

**Comment by qwertyyb** [comment]
问题已知，会尽快修复，多谢反馈，目前可先用运行playground体验
