### ISSUE TITLE
在画布上拖动组件长按组件会出现蒙层，松开鼠标后组件位置发生变化

### ISSUE THREAD

**Issue by Carloslst** [Tencent/tmagic-editor#385]
你好~~我又来了！

https://user-images.githubusercontent.com/44060788/192086408-8f7a88f7-f6cd-4802-88a8-893eba0d25e8.mp4

在画布上拖动组件长按组件会出现蒙层，松开鼠标后组件位置发生变化(变化有大有小)
有时还会出现->画布底部出现滚动条

**Comment by isensen** [comment]
长按不是出现蒙层， 是长按的时候，会选择容器，变颜色的就是当前选择的容器，你可以不松开再拖动到别的容器试一下，这样可以从容器A 拖到 容器B

**Comment by Carloslst** [comment]
> 






> 长按不是出现蒙层， 是长按的时候，会选择容器，变颜色的就是当前选择的容器，你可以不松开再拖动到别的容器试一下，这样可以从容器A 拖到 容器B
![无标题](https://user-images.githubusercontent.com/44060788/192105723-6721db8d-6d21-4677-986e-df9686d23b53.png)
嗯。。。可是我没有容器啊 这样不是导致我在拖动组件要去对齐另一个组件的时候(还没对齐)这个时候可能会变色，松手会导致我组件位置变化，而且在有其他不知名组件存在时，还会发生出现y轴滚动条出现。上图就是，这个时候整个就画布就动不了。

**Comment by Carloslst** [comment]
就是我松手后，再次从组件列表拖过去一个组件，这个时候画布高度整个就有问题了，再拖一个又变了

**Comment by Carloslst** [comment]
> 长按不是出现蒙层， 是长按的时候，会选择容器，变颜色的就是当前选择的容器，你可以不松开再拖动到别的容器试一下，这样可以从容器A 拖到 容器B
![无标题1](https://user-images.githubusercontent.com/44060788/192106266-4071f7f3-9e6d-4c30-8ec2-d97ccd664ce7.png)
就是这样

**Comment by isensen** [comment]
> > 长按不是出现蒙层， 是长按的时候，会选择容器，变颜色的就是当前选择的容器，你可以不松开再拖动到别的容器试一下，这样可以从容器A 拖到 容器B
> > ![无标题1](https://user-images.githubusercontent.com/44060788/192106266-4071f7f3-9e6d-4c30-8ec2-d97ccd664ce7.png)
> > 就是这样

page自身就是个容器， 这里确实有bug，是在pad 和 pc时，根字体计算的问题。提了一个pr #392

**Comment by Carloslst** [comment]
> > > 长按不是出现蒙层， 是长按的时候，会选择容器，变颜色的就是当前选择的容器，你可以不松开再拖动到别的容器试一下，这样可以从容器A 拖到 容器B
> > > ![无标题1](https://user-images.githubusercontent.com/44060788/192106266-4071f7f3-9e6d-4c30-8ec2-d97ccd664ce7.png)
> > > 就是这样
> 
> page自身就是个容器， 这里确实有bug，是在pad 和 pc时，根字体计算的问题。提了一个pr #392

好的，谢谢

**Comment by jia000** [comment]
#392 已在1.2.0-beta.2中包含
