### ISSUE TITLE
右侧表单配置field组件中的options是否可以根据左侧组件列表中的items动态生成

### ISSUE THREAD

**Issue by Carloslst** [Tencent/tmagic-editor#406]
你好，请问下：例如在ui组件假设是容器组件，formConfig中配置一个checkbox-group  options给空数组, 然后在拖拽组件到容器组件中，此时items有值了，是否可以根据items去动态的给options添加值

**Comment by jia000** [comment]
checkbox-group options还不支持配置成函数，可以支持一下

然后这个逻辑可以在函数里实现，目前select的options支持函数配置，可以先用select

**Comment by Carloslst** [comment]
> checkbox-group options还不支持配置成函数，可以支持一下
> 
> 然后这个逻辑可以在函数里实现，目前select的options支持函数配置，可以先用select

好的 谢谢

**Comment by Carloslst** [comment]
> > checkbox-group options还不支持配置成函数，可以支持一下
> > 然后这个逻辑可以在函数里实现，目前select的options支持函数配置，可以先用select
> 
> 好的 谢谢

> > checkbox-group options还不支持配置成函数，可以支持一下
> > 然后这个逻辑可以在函数里实现，目前select的options支持函数配置，可以先用select
> 
> 好的 谢谢

你好，好像在函数中获取不到items

**Comment by Carloslst** [comment]
> > checkbox-group options还不支持配置成函数，可以支持一下
> > 然后这个逻辑可以在函数里实现，目前select的options支持函数配置，可以先用select
> 
> 好的 谢谢

我发现在Form组件中provide('mForm', formState) 这个formState的initValues并不能在子组件/子孙组件中获取，provide Form组件的props可以获取到initValues，在initValues里面才找到items

**Comment by jia000** [comment]
`
<m-editor
    @props-panel-mounted="propsPanelMountedHandler"
  >

const propsPanelMountedHandler = async (instance: InstanceType<typeof PropsPanel>) => {
   const configForm: InstanceType<typeof MForm> = instance.refs.configForm;
  configForm.formState.xxx = xxx
}
`
可以这样去扩展formState

**Comment by Carloslst** [comment]
> xxx

这个是初始化的时候吧，那个items是拖拽组件到容器里面动态在增加

**Comment by jia000** [comment]
举个例子：你可以把editorService.get('root')等变量挂上去，然后就可以在options的函数里面获取到节点信息

**Comment by Carloslst** [comment]
> editorService

好的，我后面试一下，谢谢
