### ISSUE TITLE
tmagic-editor 开源版本默认组件有点少

### ISSUE THREAD

**Issue by gyf19** [Tencent/tmagic-editor#408]
tmagic-editor 开源版本默认组件有点少,  希望可以开发更多组件， 谢谢
![image](https://user-images.githubusercontent.com/233857/194999116-244e2cce-994d-4083-bf74-1c26584ea7c9.png)

**Comment by gyf19** [comment]
@jia000  直接关闭？，有什么解释？

**Comment by jia000** [comment]
组件需要业务方自行开发，本项目主要提供的是编辑器功能
