### ISSUE TITLE
画布宽高设置似乎无效?

### ISSUE THREAD

**Issue by fish58bf** [Tencent/tmagic-editor#42]
如图
设置宽度无效, 画布不会改变大小, 也无滚动条
![image](https://user-images.githubusercontent.com/39017213/166883098-0771b8a6-ad57-4cdc-a48b-419716608c57.png)

设置高度过小时会导致组件无法选中
![image](https://user-images.githubusercontent.com/39017213/166883756-3dbe64dc-1710-43e7-99a3-5301a4d01a1b.png)

**Comment by jia000** [comment]
画布大小是不会随页面大小改变而改变的，至于没有横滚动条确实是个问题

**Comment by xiaoCoderLJ** [comment]
画布只能是手机尺寸么，不能是PC尺寸么

**Comment by jia000** [comment]
可以配置`<m-editor :stage-rect="{width:0, height:0}"></m-editor>`来设置画布大小

**Comment by jia000** [comment]
画布横滚动条

**Comment by jia000** [comment]
画布横滚动条暂时不支持
