### ISSUE TITLE
ui库中container组件能否根据某种条件 在container.vue中动态push进去一个容器

### ISSUE THREAD

**Issue by Carloslst** [Tencent/tmagic-editor#423]
你好，再次请问一下

在ui->container中initValues中items设置[]，我再在container.vue中动态给config.items.push（{
            "id": "container_588",
            "type": "container",
            "layout": "absolute",
            "style": {
              "width": "100",
              "height": "100"
            },
            "name": "组",
            "items": []
          }）这样一个固定容器，页面会提示找不到这个组件。如果在initValues.ts   items中初始化多个固定容器是不会报错，动态添加时会报错

**Comment by jia000** [comment]
在组件里直接push，编辑器并不知道，这个时候编辑器里的dsl应该是没有push的容器的

**Comment by Carloslst** [comment]
> 在组件里直接push，编辑器并不知道，这个时候编辑器里的dsl应该是没有push的容器的

谢谢。嗯，看起来是这样，看来我只有到属性面板那边操作添加

**Comment by jia000** [comment]
可以把整体设置成一个组合组件
类似 https://github.com/Tencent/tmagic-editor/blob/master/playground/src/configs/componentGroupList.ts 里的弹窗

**Comment by Carloslst** [comment]
> 可以把整体设置成一个组合组件 类似 https://github.com/Tencent/tmagic-editor/blob/master/playground/src/configs/componentGroupList.ts 里的弹窗

我这边做得是一个分栏得效果，分栏里面都是容器，会动态的增删，还是会操作items，估计这种的弹窗是不是也不会有问题

**Comment by Carloslst** [comment]
> 增删的操作是在哪里触发的？

右侧属性面板，配置了属性row，span等number类型的filed，根据row跟span的变化来动态生成items。目前我借助dsl里面配置的data创建了一个多维数组m:[]模拟行列，吧行列存在了items里面，在ui组件中通过items的filter对应 m[i][j]传递给container看起来这样可以实现。我的ui组件中是row跟col的元素

**Comment by jia000** [comment]
可以把editorService挂到formState下，然后再field的onChange里去通过editorService.add，来添加container

**Comment by Carloslst** [comment]
> formState

我目前是通过formState 在field的onChange里去进行的items操作
