### ISSUE TITLE
请问下ui 表格开发问题

### ISSUE THREAD

**Issue by Carloslst** [Tencent/tmagic-editor#434]
![68](https://user-images.githubusercontent.com/44060788/196365812-def1ac48-ec86-4051-917b-993f09b420f5.png)
你好，请问下，我在ui中开发表格，目前表格提供的列插槽，由于ui是根据config.items去渲染，像上图这样拖拽进去组件，两列都是同时使用的一份items，会导致两列都会渲染我拖拽的组件，实际我只想在列一里面拖拽。
在目前的数据结构下感觉很难实现，能否提供下额外的思路呢

**Comment by jia000** [comment]
使用二维数组？items: [[姓名、年龄], [姓名、年龄]]

**Comment by Carloslst** [comment]
> 使用二维数组？items: [[姓名、年龄], [姓名、年龄]]
《table>
<template #bodyCell="{ column, text }">
        <template v-if="column.dataIndex === config.curDataIndex">
          <div v-if="!config.items.length && column.defineTemplate" class="m-container-placeholder">
            拖拽组件到这里
          </div>
          <template v-else>
            <vdo-ui-component
              v-for="item in config.items"
              :key="item.id"
              :config="item"
            ></vdo-ui-component>
          </template>
        </template>
      </template>
《table>
这个跟二维数组有关系吗

**Comment by Carloslst** [comment]
> > 使用二维数组？items: [[姓名、年龄], [姓名、年龄]]
> > 《table>
> > <template #bodyCell="{ column, text }">
> > 
> > 
> > 拖拽组件到这里
> > 
> > 
> > 
> > 
> > 
> > 
> > 《table>
> > 这个跟二维数组有关系吗



> 使用二维数组？items: [[姓名、年龄], [姓名、年龄]]

我i是在插槽下面直接使用的m-ui-component 跟二维数组有关系吗

**Comment by jia000** [comment]
这里4个插槽是固定的吗？如果是固定的可以将插槽理解为子组件

**Comment by Carloslst** [comment]
> 这里4个插槽是固定的吗？如果是固定的可以将插槽理解为子组件

插槽是动态的，就是展示的表格数据，我在属性栏开发了个开关，比如说我打开列1的渲染器，列一的内容全是拖拽组件到这里,，我本生表格数容器。 此时列1走插槽模式，我直接调用ui-cop，这时列1会渲染我拖拽的组件，但是我去操作列2时就有问题，因为ui-cop使用的也是items   ，  如果说是层级结构的就没问题，，，比如说 { 列1：items2 }， { 列2：items2 }

**Comment by jia000** [comment]
还是没理解到问题是什么

**Comment by Carloslst** [comment]
> 还是没理解到问题是什么

因为目前config.items不会区分是哪一列下面的items。所以无论是哪一列的操作都是同一份items数据

**Comment by Carloslst** [comment]
> 还是没理解到问题是什么

我解决了，，谢谢，麻烦了
