### ISSUE TITLE
灵活传参问题

### ISSUE THREAD

**Issue by 18664927896** [Tencent/tmagic-editor#437]
这里有几个疑问，可以解答一下么：
1，支持动态数据绑定么？ 
2，组件与组件可以传参么？
3，页面之间如何传参？
比如说我开发了一个播放器组件，那个播放链接从哪里传进来，或者我开发了一个商品组件，这些商品信息从哪里传进来，还是tmagic-editor只支持做一些比较静态的页面。

**Comment by jia000** [comment]
第一个问题，我理解是不是希望有数据源配置，支持配置变量？
第二个问题，目前支持配置事件联动，参数传递需要在组件触发事件的时候传递
第三个问题，页面之间目前是独立的，可以通过url参数传递或者是localStorage等方式传递，理论想将多个页面合并到一起也是可以的，如果是这样同通过共用@tmagic/core来做变量共享，具体得看需求了

**Comment by 18664927896** [comment]
如果我需要开发一个商品列表界面，在这个界面里面我获取到了商品列表的数据，我自定义了一个列表组件，一个商品组件，如何将他们绑定起来呢

**Comment by jia000** [comment]
要绑定什么呢？

**Comment by 18664927896** [comment]
我的意思是，可以将这两个组件套起来么

**Comment by jia000** [comment]
商品列表列表作为容器不就可以了？在容器组件内去解析items渲染商品。
