### ISSUE TITLE
导出功能

### ISSUE THREAD

**Issue by ghostgeek** [Tencent/tmagic-editor#44]
你好，
看了Playground演示页面，页面被解析成了JSON格式，引擎能否支持导出.vue 或者 .jsx格式的web代码？

**Comment by jia000** [comment]
目前并不支持导出.vue或者.jsx格式

现在是对json进行实时的动态解析，请问需要导出.vue代码的原因是啥

转成.vue代码并不难

**Comment by ghostgeek** [comment]
考虑组件的复用，在平台里可以使用，脱离平台依然可以使用。当然这只是我的想法。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/tmagic-editor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月6日(星期五) 中午11:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/tmagic-editor] 导出功能 (Issue #44)





 
目前并不支持导出.vue或者.jsx格式
 
现在是对json进行实时的动态解析，请问需要导出.vue代码的原因是啥
 
转成.vue代码并不难

**Comment by jia000** [comment]
导出.vue并不能解决“脱离平台依然可以使用“的问题啊；如果想要达到这样的效果可以对平台外的组件再封装一层接入平台才对，如：<comp-tmagic :config="config"><comp-normal ...config></comp-normal></comp-tmagic>

**Comment by ghostgeek** [comment]
好的，理解你的意思。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/tmagic-editor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月6日(星期五) 下午2:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/tmagic-editor] 导出功能 (Issue #44)





 
导出.vue并不能解决“脱离平台依然可以使用“的问题啊；如果想要达到这样的效果可以对平台外的组件再封装一层接入平台才对，如：<comp-normal ...config&gt;

**Comment by jia000** [comment]
一般需要导出代码，我理解是在没办法使用动态渲染的时候，或者是考虑动态渲染的性能不好
