### ISSUE TITLE
屏幕适配问题

### ISSUE THREAD

**Issue by 18664927896** [Tencent/tmagic-editor#442]
如何适配各个手机的屏幕，以及电脑的屏幕呢

**Comment by jia000** [comment]
目前是会根据屏幕大小计算出根节点的font-size，然后使用rem来保持组件在不同屏幕大小下等比例缩放

**Comment by 18664927896** [comment]
表单里面有left，top，right，bottom这些的单位也是rem还是px呢？

**Comment by jia000** [comment]
所有数字没有带单位的都会转成rem，具体可以看 https://tencent.github.io/tmagic-editor/docs/tutorial/render.html#%E6%B8%B2%E6%9F%93%E8%8A%82%E7%82%B9

**Comment by 18664927896** [comment]
rem是以375为基准还是可以自己配置呢？

**Comment by jia000** [comment]
默认是375，可以在runtime new Core的时候传入designWidth
