### ISSUE TITLE
关于执行release.js脚本问题

### ISSUE THREAD

**Issue by Carloslst** [Tencent/tmagic-editor#445]

**Comment by Carloslst** [comment]
你好，请问下

publishing的时候丢失了前缀
shortMessage: 'Command failed with exit code 1: npm publish --new-version 1.2.0-beta.2 --tag beta --access public',

**Comment by jia000** [comment]
没看懂问题是什么，为什么会用到release.js脚本？这个脚本是从vue3的仓库里抄来的，可以去看原版的

**Comment by Carloslst** [comment]
> 没看懂问题是什么，为什么会用到release.js脚本？这个脚本是从vue3的仓库里抄来的，可以去看原版的

源码看过了，这里是执行pnpm release会执行脚本，最终执行的是一个publish，我看到脚本里面执行后版本号的改动没问题，就是最后执行publish 没有前缀了，直接变成了1.2.0-beta.2(版本号的发布)，应该是@tmagic/具体package的name，@tmagic/editor@1.2.0-beta.2

**Comment by jia000** [comment]
没有问题啊，设置了cwd是每个包的目录

**Comment by Carloslst** [comment]
> 没有问题啊，设置了cwd是每个包的目录

update的时候是没问题，updat版本号的时候我看到是正常的，就最后publish的时候就只有版本号了
