### ISSUE TITLE
config defaultValue not work

### ISSUE THREAD

**Issue by Deuscx** [Tencent/tmagic-editor#447]
**Describe the bug**
在formConfig中defaultValue值没有生效

**To Reproduce**
使用的官方button 组件，更改如下代码：

1. formConfig
```js
export default [
  {
    text: '文本',
    name: 'text',
    defaultValue: '请输入文本内容',
  },
];
```
3. initValue

```js
export default {
  multiple: true,
  style: {
    width: '270',
    height: '37.5',
    border: 0,
    backgroundColor: '#fb6f00',
  },
};
```

**Expected behavior**
能够读取到配置的默认值

**Screenshots**
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/48537979/199178560-8e7306db-876f-4d44-8208-0ce6c568924a.png">

目前发现，只有在更改过配置后，才会读取到默认值
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/48537979/199178934-6b1ec3ae-b890-4041-9000-5a48776d667b.png">

**Comment by jia000** [comment]
defaultValue是表单的默认值并不是组件的默认值，是用来设置表单的初始状态的，如果是要作为组件的默认值应当写到initValue文件里去。

上述场景应当是在initValue中加入
`{
  text: '请输入文本内容'
}`

**Comment by Deuscx** [comment]
> 目前发现，只有在更改过配置后，才会读取到默认值

@jia000  好的，目前有另一个问题就是在再一次获取到update config的时候，是可以获取到默认值的，但第一次加载时不行。

**Comment by jia000** [comment]
第一次加载的是initValue的内容，所以第一次是加载不到formConfig里的defaultValue的
