### ISSUE TITLE
关于ui组件在画布中的问题

### ISSUE THREAD

**Issue by Carloslst** [Tencent/tmagic-editor#452]
你好，请问一下：
我在ui中封装了一个下拉选项组件，我在画布中移动到该组件会选中到我内层的input组件，会报错。
![a](https://user-images.githubusercontent.com/44060788/202664369-eddfcc7c-b2bc-485d-a4bc-b3f093b541af.png)
![b](https://user-images.githubusercontent.com/44060788/202664457-ed698174-a75d-4d55-af84-e8e7a468fe43.png)

**Comment by jia000** [comment]
可以通过canSelect 参数来控制，canSelect默认值为(el: HTMLElement) => Boolean(el.id)；
每次选中都会遍历当前鼠标位置下的所有dom，然后第一个canSelect返回true的dom会被选中；可以同过canSelect来自定义选中逻辑

**Comment by Carloslst** [comment]
> 可以通过canSelect 参数来控制，canSelect默认值为(el: HTMLElement) => Boolean(el.id)； 每次选中都会遍历当前鼠标位置下的所有dom，然后第一个canSelect返回true的dom会被选中；可以同过canSelect来自定义选中逻辑

我通过css pointer-events去处理的，嵌套了层div，在index.html再去掉pointer-events
