### ISSUE TITLE
关于部署到环境上画布无法显示

### ISSUE THREAD

**Issue by Carloslst** [Tencent/tmagic-editor#454]
不好意思，再次问一下：
 
我在playground目录下吧路由模式换成history，，，并且将editor的路径设置成了 /editor， playground的vite.config文件base也换成了 / 

'/' 目录是新创建的页面，，由这个页面点击跳转到editor，，本地无论是跳转还是直接访问/editor都是没问题，但是打包到环境上画布就无法展示了。No match found for location with path "/vdo-editor/playground/runtime/vue3/playground/index.html"

请问一下，runtime下的vue3需要手动拷贝一份到playground吗？

**Comment by jia000** [comment]
runtime的资源是不是没有部署到/vdo-editor/这个路径下？

**Comment by jia000** [comment]
或者是服务器因为支持history模式，导致/vdo-editor/playground/runtime/vue3/playground/index.html这个资源访问不到了

**Comment by Carloslst** [comment]
> runtime

runtime目录不是会打包到playground 的public下吗

**Comment by Carloslst** [comment]
> 或者是服务器因为支持history模式，导致/vdo-editor/playground/runtime/vue3/playground/index.html这个资源访问不到了

我是直接build:playground后拿的palyground下dist包

**Comment by Carloslst** [comment]
> 或者是服务器因为支持history模式，导致/vdo-editor/playground/runtime/vue3/playground/index.html这个资源访问不到了

报错倒是没有  就是画布不显示 是vue-rourter 警告的  No match found for location with path "/vdo-editor/playground/runtime/vue3/playground/index.html"，，router吧这个代理当成路由了？

**Comment by Carloslst** [comment]
> 或者是服务器因为支持history模式，导致/vdo-editor/playground/runtime/vue3/playground/index.html这个资源访问不到了

很奇怪 /vdo-editor/playground/runtime/vue3/playground/index.html 被当成了路由

**Comment by jia000** [comment]
runtimeUrl配置完整的URL，不要只是写path

**Comment by Carloslst** [comment]
> runtimeUrl配置完整的URL，不要只是写path

意思是 Editor里面的runtimeUrl与asyncLoadJs加载的umdjs都需要写成觉得路径(public下的内容)吗？

**Comment by jia000** [comment]
完整的url，例如https://tencent.github.io/tmagic-editor/playground/index.html，而不是/tmagic-editor/playground/index.html

**Comment by Carloslst** [comment]
> 完整的url，例如[https://tencent.github.io/tmagic-editor/playground/index.html，而不是/tmagic-editor/playground/index.html](https://tencent.github.io/tmagic-editor/playground/index.html%EF%BC%8C%E8%80%8C%E4%B8%8D%E6%98%AF/tmagic-editor/playground/index.html)

asyncLoadJs需要吗

**Comment by Carloslst** [comment]
> 完整的url，例如[https://tencent.github.io/tmagic-editor/playground/index.html，而不是/tmagic-editor/playground/index.html](https://tencent.github.io/tmagic-editor/playground/index.html%EF%BC%8C%E8%80%8C%E4%B8%8D%E6%98%AF/tmagic-editor/playground/index.html)

完整的的url也会被路由找不到吧

**Comment by Carloslst** [comment]
> 完整的url，例如[https://tencent.github.io/tmagic-editor/playground/index.html，而不是/tmagic-editor/playground/index.html](https://tencent.github.io/tmagic-editor/playground/index.html%EF%BC%8C%E8%80%8C%E4%B8%8D%E6%98%AF/tmagic-editor/playground/index.html)

我部署上去 完整的url也是一样的情况

**Comment by oyster0118** [comment]
@Carloslst 最后你怎么解决的啊
