### ISSUE TITLE
Module '"@tmagic/stage"' has no exported member 'CustomizeMoveableOptionsCallbackConfig'.

### ISSUE THREAD

**Issue by m13811126663** [Tencent/tmagic-editor#457]
window 11
node 14.21.0

Compiled with problems:X

ERROR in src/views/editor.vue:24:10

TS2614: Module '"@tmagic/stage"' has no exported member 'CustomizeMoveableOptionsCallbackConfig'. Did you mean to use 'import CustomizeMoveableOptionsCallbackConfig from "@tmagic/stage"' instead?
    22 | import { ComponentGroup } from '@tmagic/editor';
    23 | import { NodeType } from '@tmagic/schema';
  > 24 | import { CustomizeMoveableOptionsCallbackConfig } from '@tmagic/stage';
       |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    25 | import { asyncLoadJs } from '@tmagic/utils';
    26 |
    27 | import editorApi from '@src/api/editor';

**Comment by jia000** [comment]
@tmagic/stage 这个包是beta版本吗

**Comment by zhengyi73** [comment]
同样问题
