### ISSUE TITLE
按照官网快速开始，起不来

### ISSUE THREAD

**Issue by Freedomhxb** [Tencent/tmagic-editor#46]
```
按照官网的快速开始，运行不起来

https://tencent.github.io/tmagic-editor/docs/guide/installation.html#引入-tmagic-editor

1. vue create myapp
2. npm install @tmagic/editor@latest -S  npm install @tmagic/form@latest element-plus -S
3. 在 main.js 引入
4. npm run build 

错误如下
 error  in ./node_modules/@tmagic/form/dist/tmagic-form.es.js

Module parse failed: Unexpected token (113:18)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/conc
epts#loaders
|   }
|   return config(mForm, {
>     values: mForm?.initValues || {},
|     model: props.model,
|     parent: mForm?.parentValues || {},

 @ ./src/main.ts 11:0-37 23:8-17
 @ multi ./src/main.ts

```

**Comment by jia000** [comment]
在vue.config.js里加上transpileDependencies: [/@tmagic/]试试看

**Comment by Freedomhxb** [comment]
> 在vue.config.js里加上transpileDependencies: [/@tmagic/]试试看

不行。变成其他的报错了

**Comment by jia000** [comment]
错误信息发出来看看

**Comment by Jack-Xiexx** [comment]
> ERROR in ./node_modules/@tmagic/schema/src/index.ts 19:7
Module parse failed: Unexpected token (19:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
|
> export enum NodeType {
|   CONTAINER = 'container',
|   PAGE = 'page',
 @ ./node_modules/@tmagic/editor/dist/tmagic-editor.es.js
 @ ./src/main.js

我也遇到类似的错误，该如何处理

**Comment by jia000** [comment]
> 

这个错误就是要加上配置 transpileDependencies: [/@tmagic/]

**Comment by jia000** [comment]
> > ERROR in ./node_modules/@tmagic/schema/src/index.ts 19:7
> > Module parse failed: Unexpected token (19:7)
> > You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> > |  */
> > |
> > export enum NodeType {
> > |   CONTAINER = 'container',
> > |   PAGE = 'page',
> > @ ./node_modules/@tmagic/editor/dist/tmagic-editor.es.js
> > @ ./src/main.js
> 
> 我也遇到类似的错误，该如何处理

这个错误就是要加上配置 transpileDependencies: [/@tmagic/]

**Comment by qdu123** [comment]
我的报
Uncaught TypeError: Cannot read properties of undefined (reading 'from')
    at node_modules/safe-buffer/index.js (index.js:11:12)
    at __require2 (chunk-TMRFOBSY.js?v=32337c56:47:50)
    at node_modules/randombytes/browser.js (browser.js:15:14)
    at __require2 (chunk-TMRFOBSY.js?v=32337c56:47:50)
    at node_modules/serialize-javascript/index.js (index.js:9:19)
    at __require2 (chunk-TMRFOBSY.js?v=32337c56:47:50)
    at events.js:497:1

**Comment by SJLgogo** [comment]
> 在vue.config.js里加上transpileDependencies: [/@tmagic/]试试看

修改之后还是报错
ERROR in ./node_modules/@tmagic/schema/src/index.ts 19:7
Module parse failed: Unexpected token (19:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| 
> export enum NodeType {
|   CONTAINER = 'container',
|   PAGE = 'page',

**Comment by jia000** [comment]
> 我的报 Uncaught TypeError: Cannot read properties of undefined (reading 'from') at node_modules/safe-buffer/index.js (index.js:11:12) at __require2 (chunk-TMRFOBSY.js?v=32337c56:47:50) at node_modules/randombytes/browser.js (browser.js:15:14) at __require2 (chunk-TMRFOBSY.js?v=32337c56:47:50) at node_modules/serialize-javascript/index.js (index.js:9:19) at __require2 (chunk-TMRFOBSY.js?v=32337c56:47:50) at events.js:497:1

npm i buffer 应该就可以了，这问题已经解决过了，只是npm包还没发布新的

**Comment by jia000** [comment]
@SJLgogo 不是ts项目？

**Comment by qdu123** [comment]
> > 我的报 Uncaught TypeError: Cannot read properties of undefined (reading 'from') at node_modules/safe-buffer/index.js (index.js:11:12) at __require2 (chunk-TMRFOBSY.js?v=32337c56:47:50) at node_modules/randombytes/browser.js (browser.js:15:14) at __require2 (chunk-TMRFOBSY.js?v=32337c56:47:50) at node_modules/serialize-javascript/index.js (index.js:9:19) at __require2 (chunk-TMRFOBSY.js?v=32337c56:47:50) at events.js:497:1
> 
> npm i buffer 应该就可以了，这问题已经解决过了，只是npm包还没发布新的

感谢感谢！
不过现在出现
Uncaught ReferenceError: global is not defined
    at node_modules/randombytes/browser.js (browser.js:16:14)
    at __require2 (chunk-LTPURSQW.js?v=9febb0af:18:50)
    at node_modules/serialize-javascript/index.js (index.js:9:19)
    at __require2 (chunk-LTPURSQW.js?v=9febb0af:18:50)
    at events.js:497:1

**Comment by qdu123** [comment]
> > 我的报 Uncaught TypeError: Cannot read properties of undefined (reading 'from') at node_modules/safe-buffer/index.js (index.js:11:12) at __require2 (chunk-TMRFOBSY.js?v=32337c56:47:50) at node_modules/randombytes/browser.js (browser.js:15:14) at __require2 (chunk-TMRFOBSY.js?v=32337c56:47:50) at node_modules/serialize-javascript/index.js (index.js:9:19) at __require2 (chunk-TMRFOBSY.js?v=32337c56:47:50) at events.js:497:1
> 
> npm i buffer 应该就可以了，这问题已经解决过了，只是npm包还没发布新的

感谢感谢！
不过现在出现
Uncaught ReferenceError: global is not defined
    at node_modules/randombytes/browser.js (browser.js:16:14)
    at __require2 (chunk-LTPURSQW.js?v=9febb0af:18:50)
    at node_modules/serialize-javascript/index.js (index.js:9:19)
    at __require2 (chunk-LTPURSQW.js?v=9febb0af:18:50)
    at events.js:497:1

哪位大佬给个能跑起来的工程，谢谢！

**Comment by jia000** [comment]
global is not defined

**Comment by jia000** [comment]
1.0.0-beta.14 已发布

**Comment by SJLgogo** [comment]
是的&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月7日(星期六) 下午2:04
收件人: ***@***.***&gt;; 
抄送: " ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tencent/tmagic-editor] 按照官网快速开始，起不来 (Issue #46)





 
@SJLgogo 不是ts项目？

**Comment by lxt-ing** [comment]
请问一下react+webpack项目遇到这个You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. 要怎么处理呢

**Comment by ashen9** [comment]
为啥我用的1.2.0版本还是有这个问题
Uncaught ReferenceError: global is not defined
    at node_modules/.pnpm/randombytes@2.1.0/node_modules/randombytes/browser.js (browser.js:16:14)
    at __require (chunk-FQZ6OWVD.js?v=86dc4da2:11:50)
    at node_modules/.pnpm/serialize-javascript@6.0.0/node_modules/serialize-javascript/index.js (index.js:9:19)
    at __require (chunk-FQZ6OWVD.js?v=86dc4da2:11:50)
    at events.js:497:1

**Comment by JustGogoing** [comment]
```js
"@tmagic/design": "^1.2.15",
    "@tmagic/editor": "^1.2.15",
    "@tmagic/element-plus-adapter": "^1.2.15",
    "@tmagic/form": "^1.2.15",
    "@tmagic/stage": "^1.2.15",
    "element-plus": "^2.3.8",
    "pinia": "^2.1.4",
    "vue": "^3.3.4",
    "vue-router": "^4.2.4"
```
问题依然存在，使用polyfills解决
