### ISSUE TITLE
新增页面的时候报错

### ISSUE THREAD

**Issue by Wangjing991** [Tencent/tmagic-editor#460]
![image](https://user-images.githubusercontent.com/19301714/206389271-b36fb4be-7cf2-4e4c-bb34-58aaed23f7a7.png)

**Comment by jia000** [comment]
v-model是不是没有初始值？初始值应该至少要有{ type: 'app', items: [], id: xxx }

**Comment by jia000** [comment]
页面是生成的，生成的页面是放到 app的items数组里
