### ISSUE TITLE
请问useAddField的作用是什么？

### ISSUE THREAD

**Issue by Bobi-zhou** [Tencent/tmagic-editor#462]
我看在form组件里面的Field都调用了
``` javascript
useAddField(props.prop);
```
但是在editor里面的Field 又没有调用该方法，请问什么时候该调用这个方法。

**Comment by jia000** [comment]
在form config中配置的函数一般第一个参数是formState，可以通过formState.getField()来获取到组件实例，这个就是useAddField做的，将实例保存到form中；如果不需要获取组件实例这样的诉求可以不管useAddField

**Comment by Bobi-zhou** [comment]
明白了，这样是不是在一个组件的onChange触发的时候，可以在这个onChange里面，通过formState.getField()获取另外一个组件的实例，从而来改变另外一个组件的值。

**Comment by jia000** [comment]
是的，但是如果只是要改变组件的值，改变model或者formValue就行，不需要使用组件实例
