### ISSUE TITLE
package下面的组件引入其他组件打包路劲问题，麻烦帮我看下这个问题呢。谢谢

### ISSUE THREAD

**Issue by mmclofe** [Tencent/tmagic-editor#464]
文档中介绍：
![image](https://user-images.githubusercontent.com/44460247/207359089-6471d174-10e8-498a-b899-fb66d1ad3473.png)
因为这是个提交组件，要用到各组件。我们按照文档中配置打包引入ui下面的组件
![image](https://user-images.githubusercontent.com/44460247/207358974-bd7b3adc-b549-496a-b1ec-6b2bc84e3eab.png)
但是打包出来的路劲变成了本地目录
![image](https://user-images.githubusercontent.com/44460247/207359553-4af71675-2855-4d54-811b-5d5eb8458bc4.png)
麻烦帮我看下这个问题呢。谢谢

**Comment by jia000** [comment]
packages可以配置成npm包名
