### ISSUE TITLE
在组件面板中点击组件时，在画布中显示对应的组件，但是直接按键盘向右键头没反应

### ISSUE THREAD

**Issue by dingxiaobu** [Tencent/tmagic-editor#468]
在组件面板中点击组件时，在画布中显示对应的组件，但是直接按键盘向右箭头键没反应，非得需要用鼠标拖动一下，再按向右的箭头键时才能向右移动

**Comment by jia000** [comment]
需要鼠标移到画布上才能激活方向键，不需要用鼠标拖一下

**Comment by dingxiaobu** [comment]
> 

亲测多次bug，鼠标上下键是可以让组件移动的，向右箭头是移动不了的。

https://user-images.githubusercontent.com/7554035/209284454-9bcc2c2c-9f6d-457b-9748-d4742828a1a3.mp4

**Comment by dingxiaobu** [comment]
针对这个问题还有点可能需要完善，点左边组件时，应该让画布加上焦点，直接按上下左右键就可以移动组件了，这样体验就更好了。
