### ISSUE TITLE
在playground下npm run build。dist目录下得不到runtime文件夹

### ISSUE THREAD

**Issue by LdPz-ROOM** [Tencent/tmagic-editor#479]
在管理端中我们提供了一个可视化的模拟画布，他需要依赖 runtime 核心库，因此我们需要先在 magic 根目录下运行

```js
cd magic
npm run build
```

将 /playground/dist/runtime 文件夹复制到 /magic-admin/web/public 和 /magic-admin/server/assets 目录下。web 下的 runtime 提供给模拟画布使用，server 下的 runtime 提供给发布后的页面来使用。

**Comment by jia000** [comment]
文档描述不准确，应该是 npm run build:runtime:admin，然后将/runtime/vue3|vue2|react/dist 复制到  /magic-admin/serve/static中

**Comment by LdPz-ROOM** [comment]
怎么样才能唤管理端可视化的模拟画布，按照上面步骤执行，启动后台还是看见的创建项目的界面，这一块相关的有文档吗
