### ISSUE TITLE
关于添加动态数据源绑定功能的支持想法

### ISSUE THREAD

**Issue by WangMingHua111** [Tencent/tmagic-editor#481]
我使用该开源库的过程中，在自己的项目中添加了一个对该开源库无侵入性的功能超集（数据集、数据源、数据值设置，动态数据源（api、ws）、数据源绑定表单组件等组成的动态数据源绑定功能），支持对文本字段、列表数据、表格数据进行网络数据的绑定。
不知目前贵开源库是否已经在添加该功能，由于目前处于失业中，有闲暇的时间，将以前写的功能整合到贵库中，由于需要耗费些时间整合，所以先开了个Issues来反馈我的想法。

[示例地址：](https://dv.wangminghua.com/)https://dv.wangminghua.com/

效果图如下：
文本字段：
![image](https://user-images.githubusercontent.com/51693922/218951709-0a8edaba-9289-4d85-bc5e-b5863fb75d79.png)
![image](https://user-images.githubusercontent.com/51693922/218951841-c8afb336-9293-409a-bc16-764914edb512.png)
效果预览：
![image](https://user-images.githubusercontent.com/51693922/218951917-7157c65e-488b-4f19-a13c-c2db504f3de8.png)
![image](https://user-images.githubusercontent.com/51693922/218952126-bb51030f-960a-4ebc-9121-78fae5ca617b.png)

列表字段：
![image](https://user-images.githubusercontent.com/51693922/218952345-f4f3a4a1-2d65-48f4-ae36-7cda1bbc599b.png)
效果预览：
![image](https://user-images.githubusercontent.com/51693922/218952475-301b91fe-b5a7-4d5f-93bd-86d167455258.png)

数据表字段：
![image](https://user-images.githubusercontent.com/51693922/218952701-6ab6d4c2-3e79-4553-8fb0-32537a4a56ca.png)
效果预览：
![image](https://user-images.githubusercontent.com/51693922/218952778-9992eba7-2a71-4d88-be94-3319c9bcfcac.png)

**Comment by oceanzhu** [comment]
赞，作为维护方，我们近期正有规划该功能

**Comment by jia000** [comment]
[示例地址：](https://dv.wangminghua.com/)https://dv.wangminghua.com/
很棒的想法与实现

数据源功能已经在规划中，计划近期实现，欢迎贡献宝贵的想法与代码

**Comment by jia000** [comment]
数据源功能是属于比较大的功能，建议先将其拆分，然后一起一一讨论对齐实现，例如：DSL的设计，组件中的实现（不同框架的实现），编辑中的交互（如何关联数据源，如果绑定字段），数据源声明周期，数据源作用域，等等这些问题

**Comment by WangMingHua111** [comment]
> 数据源功能是属于比较大的功能，建议先将其拆分，然后一起一一讨论对齐实现，例如：DSL的设计，组件中的实现（不同框架的实现），编辑中的交互（如何关联数据源，如果绑定字段），数据源声明周期，数据源作用域，等等这些问题

恩，我也不确定贵方已经实现到了什么程度，我先将数据源的核心代码贴到这里，你看下是否和你们的设计理念冲突。

通过 d.ts 声明问题给node节点拓展了2个字段
![image](https://user-images.githubusercontent.com/51693922/218958685-6204cbc3-196e-4724-88cd-3f2b85b918e1.png)


![image](https://user-images.githubusercontent.com/51693922/218957292-4da988fc-e14d-4bb2-aa9d-455611ffcd36.png)

[DataSet ](http://oss.wangminghua.com:9090/test/data-source.ts) 是个独立的ts类：

**Comment by WangMingHua111** [comment]
其他的都是基于该核心的上层运用

**Comment by jia000** [comment]
数据源加载的时机是什么？在页面渲染之前？

**Comment by WangMingHua111** [comment]
在这里我简单描述一下数据源的工作原理：

通过编辑器创建 DSL 这个流程不变，在页面渲染前，遍历DSL每一个节点，如果节点（MNode）需要绑定数据源（bind = true 且 节点数据绑定映射字段attrs有效），则通过Proxy包装MNode节点，做属性拦截并替换需要映射（attrs列表）的属性（reactive）。

然后有数据源更新时，重新赋值reactive对象。
![image](https://user-images.githubusercontent.com/51693922/218985918-7751becf-7c15-44a1-a53c-e6a8faf34236.png)

**Comment by WangMingHua111** [comment]
每个数据集包含了多个数据源，数据集负责数据的读取（只读），数据源对象负责数据的写入（只写），读写分离
![image](https://user-images.githubusercontent.com/51693922/218987827-7edfd091-d88d-402f-b937-1d9ded3cd8d2.png)

![image](https://user-images.githubusercontent.com/51693922/218988024-f10db762-8fcf-4417-b5d9-e9f962b89047.png)
![image](https://user-images.githubusercontent.com/51693922/218988184-e7466dab-3b66-4241-8c56-3a41e35c9512.png)

**Comment by jia000** [comment]
只要有数据源更新就重新执行一下setDataSet? 这样做不会有性能问题吗？

**Comment by WangMingHua111** [comment]
setDataSet 仅需要调用一次，主要目的是为了替换需要代理的MNode的属性从ds中读取，其中ds使用的是观察者模式，数据更新则是依赖于 vue 的 reactive 机制，我认为基本无性能损耗问题，而数据的更新频是由有数据源配置决定，由于我目前仅使用的vue，像react等，可以做个适配插件或者接口来替换vue专有的reactive机制

**Comment by WangMingHua111** [comment]
#485 这是我先提交的支持数据源绑定的核心，我在源码中添加了测试代码，请不要合并，先拉取下来测试一下。

**Comment by WangMingHua111** [comment]
另外能否在QQ群中联系到你们，我好平凡截图之类的描述的想法和测试用例。

**Comment by jia000** [comment]
> 

可以的联系官方小助手就行了

**Comment by WangMingHua111** [comment]
[添加了通用响应式模块，同时将数据源中的Data对象包装为响应式对象，由运行时决定。当前支持vue2、vue3、react响应式更新](https://github.com/Tencent/tmagic-editor/pull/485/commits/5fd8d6d3db9a92cbb6a8b9fc0cced4e8fce791ea)

**Comment by WangMingHua111** [comment]
已移除第三方响应式框架，添加了自定义响应式模块
