### ISSUE TITLE
教程中的代码更新

### ISSUE THREAD

**Issue by yockii** [Tencent/tmagic-editor#495]
1、@tmagic/form 在use的时候应为 use(TMagicForm, {})
```
createApp(App)
  .use(ElementPlus)
  .use(TMagicEditor)
  .use(TMagicForm, {})
  .mount('#app');
```
2、hello world 不出意外肯定会有意外报错：
Uncaught ReferenceError: global is not defined
还是要写明解决方法（个人解决方案如下）
src下新建 polyfills.ts 
```
if (typeof (window as any).global === 'undefined') {
  (window as any).global = window
}
```
在main.ts第一行引入
```
import './polyfills'
```
3、modelValue按示例给了初始值后，点击新增页面时无法渲染画布的，会报错，curNode为null，这个应该是bug需要修复的
初始值改为如下可以正常显示，但删除页面会有问题
```
const value = ref({
  type: 'app',
  items: [
    {
      type: 'page',
      name: 'page_1',
      id: 'page_1',
      items: []
    }
  ],
});
```
4、render中，root.id = `${page.value.id}` 会报错，改为 ${page.id} 即可

很遗憾，最后，根据教程并未成功搭建editor。还要继续研究

**Comment by jia000** [comment]
> Uncaught ReferenceError: global is not defined

如果使用vite，可以配置
```
  optimizeDeps: {
    esbuildOptions: {
      define: {
        global: 'globalThis',
      },
    },
  },
```

**Comment by jia000** [comment]
type: 'app' 直接加上id: 'xxx'

**Comment by yockii** [comment]
好的，我先按照这个方案处理。后续遇到问题再开新的issue
