### ISSUE TITLE
组件内代码与editor通信

### ISSUE THREAD

**Issue by toadprince** [Tencent/tmagic-editor#499]
需求描述：
一个组件需要依赖另一个组件，组件内部代码在判断到app.platform为editor，且尚未添加所依赖的组件时，提示并让editor自动创建一个所依赖的组件

请问能这样通信吗？

**Comment by jia000** [comment]
编辑中可以通过```editorService.get('stage')?.renderer.runtime?.getApp?.()```来获取到app，然后就可以通过app来做通讯

**Comment by microNewLife** [comment]
请问组件内部如何获取到editorService呢？看了下示例，有注入app，但是没有各类service的注入
