### ISSUE TITLE
关于编辑器扩展

### ISSUE THREAD

**Issue by Frankiness** [Tencent/tmagic-editor#507]
你好，请问编辑器扩展这部分文档没有吗

**Comment by jia000** [comment]
扩展可以有如下几种方式：
1. 通过xxService.usePlugin的方式，修改编辑的默认行为例如：

```js
editorService.usePlugin({
  beforeDoAdd(config, parent) {
   //  修改新增组件时的参数
    return [newConfig, newParent]
 }
})

具体哪些api支持修改，可以看api文档或者直接看service的代码

```

2. 传入slot

可以查看 https://tencent.github.io/tmagic-editor/docs/api/editor/slots.html

3. 通过配置props

https://tencent.github.io/tmagic-editor/docs/api/editor/props.html
