### ISSUE TITLE
如何扩展样式面板里的样式选项

### ISSUE THREAD

**Issue by toadprince** [Tencent/tmagic-editor#508]
如题，在不修改packages里源码的情况下，如何扩展样式面板里的样式选项，比如新增border-radius的样式

**Comment by jia000** [comment]
可以通过重写propsService.fillConfig来完全自己定制属性配置
```
propsService.usePlugin({
  /**
   oldConfig: 系统生成的配置
   componentConfig: 组件内定义的formConfig
   **/
  afterFillConfig(oldConfig, componentConfig) {
    return yourConfig
  }
})
```

[点击查看系统生成的实现](https://github.com/Tencent/tmagic-editor/blob/master/packages/editor/src/utils/props.ts)

**Comment by hellowalker** [comment]
> 可以通过重写propsService.fillConfig来完成自己的自定义属性配置
> 
> ```
> propsService.usePlugin({
>   /**
>    oldConfig: 系统生成的配置
>    componentConfig: 组件内定义的formConfig
>    **/
>   afterFillConfig(oldConfig, componentConfig) {
>     return yourConfig
>   }
> })
> ```
> 
> [点击查看系统生成的实际情况](https://github.com/Tencent/tmagic-editor/blob/master/packages/editor/src/utils/props.ts)

添加后 右侧面板有出现选项 但是配置选项数据没有体现在dsl里 怎么解决呢？

**Comment by jia000** [comment]
请提供详细的信息

**Comment by toadprince** [comment]
> 可以通过重写propsService.fillConfig来完全自己定制属性配置
> 
> ```
> propsService.usePlugin({
>   /**
>    oldConfig: 系统生成的配置
>    componentConfig: 组件内定义的formConfig
>    **/
>   afterFillConfig(oldConfig, componentConfig) {
>     return yourConfig
>   }
> })
> ```
> 
> [点击查看系统生成的实现](https://github.com/Tencent/tmagic-editor/blob/master/packages/editor/src/utils/props.ts)

这样可以扩展右侧面板，[文档](https://tencent.github.io/tmagic-editor/docs/guide/editor-expand.html#ui%E6%89%A9%E5%B1%95)中也有。
