### ISSUE TITLE
此插件支持vue2吗?

### ISSUE THREAD

**Issue by prettygirlya** [Tencent/tmagic-editor#509]
文档上面写的支持vue2  但是vue2安装的依赖需要vue3  
<img width="1011" alt="image" src="https://github.com/Tencent/tmagic-editor/assets/47108785/54f17e75-a8cb-4ab6-bc96-ea02973b66c0">
![image](https://github.com/Tencent/tmagic-editor/assets/47108785/9df9a070-c643-4eae-b26e-7d1d8bb2cc23)

**Comment by jia000** [comment]
编辑器是不支持vue2的，只有runtime支持，runtime是dsl的执行环境

**Comment by prettygirlya** [comment]
好的,谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/tmagic-editor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月25日(星期四) 下午5:13
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Tencent/tmagic-editor] 此插件支持vue2吗? (Issue #509)





 
编辑器是不支持vue2的，只有runtime支持，runtime是dsl的执行环境
