### ISSUE TITLE
新增数据源后的push，执行bootstrap会报错

### ISSUE THREAD

**Issue by toadprince** [Tencent/tmagic-editor#510]
feat: 新增数据源，clone这个push后，执行bootstrp报如下错误：

│ npm ERR! Lifecycle script `build:type` failed with error:                                                                                                            
│ npm ERR! Error: command failed
│ npm ERR!   in workspace: @tmagic/editor@1.2.15 
│ npm ERR!   at location: D:\中科院\onesis\tmagic-editor-20230529\packages\editor 
└─ Failed in 11.8s
D:\中科院\onesis\tmagic-editor-20230529\packages\editor:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @tmagic/editor@1.2.15 build: `npm run build:type && vite build`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.

**Comment by jia000** [comment]
到editor目录下build，把详细的错误信息发来看下

```bash
cd packages/editor
npm run build
````

**Comment by jia000** [comment]
更新到最新代码后需要npm run reinstall，重新装一下依赖

**Comment by toadprince** [comment]
> 更新到最新代码后需要npm run reinstall，重新装一下依赖

我是重新clone的，然后执行的bootstrap

**Comment by toadprince** [comment]
> 

src/fields/CodeSelect.vue:10:20 - error TS2440: Import declaration conflicts with local declaration of 'defineEmits'.

10 import { computed, defineEmits, defineProps, watch } from 'vue';
                      ~~~~~~~~~~~

src/fields/CodeSelect.vue:10:33 - error TS2440: Import declaration conflicts with local declaration of 'defineProps'.

10 import { computed, defineEmits, defineProps, watch } from 'vue';
                                   ~~~~~~~~~~~

src/fields/CodeSelectCol.vue:20:20 - error TS2440: Import declaration conflicts with local declaration of 'defineEmits'.

20 import { computed, defineEmits, defineProps, inject, ref, watch } from 'vue';
                      ~~~~~~~~~~~

src/fields/CodeSelectCol.vue:20:33 - error TS2440: Import declaration conflicts with local declaration of 'defineProps'.

20 import { computed, defineEmits, defineProps, inject, ref, watch } from 'vue';
                                   ~~~~~~~~~~~

src/fields/EventSelect.vue:37:20 - error TS2440: Import declaration conflicts with local declaration of 'defineProps'.

37 import { computed, defineProps, inject } from 'vue';
                      ~~~~~~~~~~~


Found 5 errors in 3 files.

Errors  Files
     2  src/fields/CodeSelect.vue:10
     2  src/fields/CodeSelectCol.vue:20
     1  src/fields/EventSelect.vue:37
npm ERR! Lifecycle script `build:type` failed with error: 
npm ERR! Error: command failed
npm ERR!   in workspace: @tmagic/editor@1.2.15
npm ERR!   at location: D:\中科院\onesis\tmagic-editor-20230529\packages\editor
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed
npm ERR!   in workspace: @tmagic/editor@1.2.15
npm ERR!   at location: D:\中科院\onesis\tmagic-editor-20230529\packages\editor

**Comment by jia000** [comment]
等一下会发一下提交修复

**Comment by toadprince** [comment]
> 等一下会发一下提交修复

vue版本问题？感觉也不像啊，我回退到以往的commits也一样的报错

**Comment by jia000** [comment]
升级了vue3.3会出现这个错误，这里的代码也有不妥，不应该去import defineEmit

**Comment by jia000** [comment]
已修复
