### ISSUE TITLE
希望能将由原子组件拼凑而成的大组件保存，从而复用

### ISSUE THREAD

**Issue by wrr008123** [Tencent/tmagic-editor#511]
如原子组件 "组" "文本" "图片" "按钮"拼凑成了一个A

我们将 A 视为一个大组件，希望能将A组件保存下来，以便于后续其他页面也使用

**Comment by jia000** [comment]
可以参考playground中的弹窗组件

**Comment by wrr008123** [comment]
> 可以参考playground中的弹窗组件

从开发角度的确是可以参考弹窗组件的，但是我的请求是从一个非开发的角度提出的，希望能够复用自己自定义的（开发无法满足每一个营销人员的脑洞而去开发各种各样的组件）

假如我是一名营销人员，我希望的是我在A营销页搭建的一些内容，能在B营销页上使用，或者说只是使用它的布局样式（内容重新修改），很明显我不希望再去搭建一次

**Comment by jia000** [comment]
这个你得去做一个保存为组件的功能啊，然后要根据当前选择的组件去生成一个新的组件模板配置
