### ISSUE TITLE
关于Page容器等属性固定的问题

### ISSUE THREAD

**Issue by joey127yao** [Tencent/tmagic-editor#513]
基于业务需求, Page容器这块需要固定容器面板展示, __不允许设置__ 他的各个属性样式,有办法实现吗？

目前关于Page的盒子宽高大小,目前我的解决方案可能就是修改 `packages/ui/src/page/src/index.vue` 对应的属性设置,
其他的属性暂时没有思路。 

想了解下有没有更好的方案,是否方便告知？  非常感谢！

**Comment by jia000** [comment]
formConfig里设置disable: true

其他公共的配置需要通过propsService去设置

**Comment by joey127yao** [comment]
可能我没描述清楚,想要的是编辑器 如果组件是 Page的情况下,不给设置各个属性以及拖拽。右侧栏目的属性面板禁用状态,数据不给修改。
目前根据你的建议,去配置了disabled, 右侧栏目的属性面板确实可以禁用，但是编辑器容器的拖拽问题还是会修改 属性的宽度大小,有办法解决吗？

期望效果:  
  当组件是Page的时候,没有拖拽框 + 属性面板的样式模块是禁用状态

<img width="492" alt="image" src="https://github.com/Tencent/tmagic-editor/assets/41769296/8be27f2c-a348-487f-82e8-d57894c00f37">

<img width="1010" alt="image" src="https://github.com/Tencent/tmagic-editor/assets/41769296/c9b6ee72-fcba-4c2b-bde4-81e9c96f2a5f">

**Comment by jia000** [comment]
拖拽可以通过[moveableOptions](https://tencent.github.io/tmagic-editor/docs/api/editor/props.html#moveableoptions) prop去控制，文档里有示例
