### ISSUE TITLE
联动组件的无法选择到对应的组件

### ISSUE THREAD

**Issue by ah-wq** [Tencent/tmagic-editor#514]
现象：联动组件的无法选择到对应的组件，
![截屏2023-06-05 19 58 08](https://github.com/Tencent/tmagic-editor/assets/20314753/7bbf418f-c18f-40d3-8881-150c2ea32363)

![截屏2023-06-05 19 58 42](https://github.com/Tencent/tmagic-editor/assets/20314753/f8e6741f-af5d-48e9-ae41-535383040b57)

复现步骤
在事件面板，选择点击，选择组件，组件联动点击选择，无法进一步选择关联组件
         将已有的联动组件删除后也同样无法添加
https://tencent.github.io/tmagic-editor/playground/index.html#/

**Comment by jia000** [comment]
需要再画布或者组件树中选择组件啊

**Comment by ah-wq** [comment]
选择了的
![截屏2023-06-06 09 03 26](https://github.com/Tencent/tmagic-editor/assets/20314753/c285968e-074e-4c10-80ab-e4114029d447)

**Comment by jia000** [comment]
点了“点击此处选择”后，再去画布或者组件树里选组件
