### ISSUE TITLE
关于Page容器布局问题

### ISSUE THREAD

**Issue by Frankiness** [Tencent/tmagic-editor#515]
### 我已修改formConfig中布局属性，但未生效
![image](https://github.com/Tencent/tmagic-editor/assets/50985788/03f9b468-69e7-4668-a91b-33b55232ba2c)
![image](https://github.com/Tencent/tmagic-editor/assets/50985788/4931c5d6-63d6-47e0-9982-193c14247867)

**Comment by jia000** [comment]
去packages/ui/src/page/src/initValue.ts里加上 layout: relative

**Comment by Frankiness** [comment]
> 去packages/ui/src/page/src/initValue.ts里加上 layout: relative

依然无效，page下的元素仍然是absolute定位
![image](https://github.com/Tencent/tmagic-editor/assets/50985788/3f385ac7-2fe2-41e2-a30b-45b23c515c5d)
