### ISSUE TITLE
是否有计划 组件显示/隐藏功能

### ISSUE THREAD

**Issue by joey127yao** [Tencent/tmagic-editor#516]
想要让组件有类似PS的图层显隐的效果, 点击显示或者 隐藏。
https://github.com/Tencent/tmagic-editor/issues/368 这个Issue有提及，但是好像没看到相关的 显影功能代码，想问问是否有在计划内？

**Comment by jia000** [comment]
具体实现是希望：隐藏后在发布的页面里也隐藏还是仅在编辑器里隐藏？

**Comment by jia000** [comment]
一直都想加，就是纠结不同的业务可能对这个隐藏的理解不一样，类似是希望v-show还是v-if

**Comment by joey127yao** [comment]
希望的效果是 两者都隐藏，
在点击对应图层的隐藏按钮, 在编辑器的 展示层 、预览效果、以及对应的发布页面都是隐藏效果,同时有个图层状态变量展示对应变更
<img width="1211" alt="image" src="https://github.com/Tencent/tmagic-editor/assets/41769296/0422d8d5-55d7-4425-9b1d-d8b0e217598f">
