### ISSUE TITLE
 Error: Secure random number generation is not supported by this browser.

### ISSUE THREAD

**Issue by zane0904** [Tencent/tmagic-editor#517]
w10系统
 node  v18.15.0
pnpm  v8.6.2
通过 pnpm create vite@latest  新的项目
vite 4.3.9
vue 3.2.47
按照文档 https://tencent.github.io/tmagic-editor/docs/guide/ 快速开始搭建的项目在启动后报错
Uncaught Error: Secure random number generation is not supported by this browser.
Use Chrome, Firefox or Internet Explorer 11

发现是这个插件 @tmagic/editor 报的错 把这个注释掉 没有这个错误 mac系统也尝试了 都是同样的问题 请问是哪里出的问题？
是否与serialize-javascript有关？
![image](https://github.com/Tencent/tmagic-editor/assets/41895910/d9b42c7c-6aac-466a-b739-ed18b81ff671)

![image](https://github.com/Tencent/tmagic-editor/assets/41895910/7b7c7abc-e4eb-456d-803e-69678a1c1633)

**Comment by jia000** [comment]
使用的是什么浏览器？换最新版的chrome试试？上述提供的环境无法复现此问题

**Comment by zane0904** [comment]
> 

是最新的浏览器 谷歌 edge都不行 你是用的什么环境搭建的？

**Comment by jia000** [comment]
![image](https://github.com/Tencent/tmagic-editor/assets/4327396/39278033-9eb6-45a6-868f-39047ad73b55)
这个错误是 ```randombytes``` 这个包报的，从源码上看是判断是否有```crypto.getRandomValues```，可直接在浏览器控制台中直接运行```crypto.getRandomValues```看看是否支持
![image](https://github.com/Tencent/tmagic-editor/assets/4327396/5e1a8c47-cf6a-4d71-a009-74b9a78cb035)

**Comment by jia000** [comment]
再vite.config中是否有加入配置：
```js
optimizeDeps: {
    esbuildOptions: {
      define: {
        global: 'globalThis',
      },
    },
  },
```

**Comment by zane0904** [comment]
> 再vite.config中是否有加入配置：
> 
> ```js
> optimizeDeps: {
>     esbuildOptions: {
>       define: {
>         global: 'globalThis',
>       },
>     },
>   },
> ```

是这个问题 加上去
define: {
        global: 'globalThis',
      },
  就可以了 谢谢
