### ISSUE TITLE
runtime 组件目录替换为npm包名报错

### ISSUE THREAD

**Issue by ah-wq** [Tencent/tmagic-editor#520]
官方demo
runtime/vue2
![截屏2023-07-04 14 51 16](https://github.com/Tencent/tmagic-editor/assets/20314753/585d901f-1792-4ccb-80ca-8e78938f6772)
会提示.Could not resolve entry module ".tmagic/value-entry.ts 
等相关.tmagic目录下的文件找不到

**Comment by jia000** [comment]
https://github.com/Tencent/tmagic-editor/commit/bb682cb2d7fc16c953d2d07d85151339cc1f2401
