### ISSUE TITLE
【BUG】设置禁用拖拽效果,键盘事件仍生效

### ISSUE THREAD

**Issue by joey127yao** [Tencent/tmagic-editor#521]
moveableOptions.draggable 配置不允许拖拽
现状: 
       鼠标不可以拖动,但可以通过键盘的方向键进行方位调整，并触发了属性的方位修改。
期望: 
       方位属性值键盘事件不生效

**Comment by jia000** [comment]
更新到 v1.2.0-alpha.10

然后加上如下代码

`editorService.usePlugin({
  beforeDoUpdate(config: MNode) {
    const stage = editorService.get('stage');
    if (!stage?.getMoveableOption('draggable') && config.style) {
      delete config.style.left;
      delete config.style.top;
      delete config.style.right;
      delete config.style.bottom;
    }
    return [config];
  },
});`
