### ISSUE TITLE
数据源没有自动提示

### ISSUE THREAD

**Issue by Frankiness** [Tencent/tmagic-editor#530]
## 当创建多个数据源时，变量input框无法自动补全
![image](https://github.com/Tencent/tmagic-editor/assets/50985788/4dbee446-3611-4cb9-b21e-67d83601452a)

**Comment by jia000** [comment]
是否有报错？

数据源配置发一下

**Comment by Frankiness** [comment]
未提示错误
我在官网playground下操作也会出现这种情况：
![image](https://github.com/Tencent/tmagic-editor/assets/50985788/2db97e3b-3797-496a-bf37-2a6943c05efc)

dsl配置如下：
`dataSources: [
    {
      id: "ds_b64c92b5",
      type: "base",
      title: "button",
      description: "按钮",
      fields: [
        {
          type: "string",
          name: "text",
          title: "按钮文案",
          description: "",
          defaultValue: "打开弹窗"
        }
      ]
    },
    {
      id: "ds_c6a6e8fc",
      type: "base",
      title: "test",
      description: "",
      fields: [
        {
          type: "string",
          name: "plan",
          title: "plan",
          description: "",
          defaultValue: "计划计划",
          enable: true,
          fields: []
        }
      ],
      methods: []
    }
  ],
  dataSourceDeps: {
    ds_b64c92b5: {},
    ds_c6a6e8fc: {
      button_430: {
        name: "按钮",
        keys: [
          "text"
        ]
      }
    }
  },
  dataSourceCondDeps: {
    ds_b64c92b5: {},
    ds_c6a6e8fc: {}
  }`

**Comment by Frankiness** [comment]
推测是

> DataSourceInput.vue 下 fieldQuerySearch 函数使用 keys.shift() 的原因
