### ISSUE TITLE
联动表单修改时对就UI不能更新

### ISSUE THREAD

**Issue by lcocov** [Tencent/tmagic-editor#534]
联动表单修改时，对应的form可以修改，但如果修改的form在UI有双向绑定。对应的UI并不能双向绑定。

**Comment by jia000** [comment]
请具体描述一下，最好能有示例

**Comment by longer008** [comment]
我也想知道

**Comment by jia000** [comment]
这种情况需要触发一下form的chang事件
`handler:  (vm, { model }) => {
  model.text = 'xxxt';
  vm.$emit('change')
})
`

**Comment by lcocov** [comment]
好的，如果我要做联动。改变其它表单的字段，怎么触发change事件呢。

**Comment by lcocov** [comment]
谢谢已解决！
