### ISSUE TITLE
如何通过 http 数据源传入数组或其他类型数据？

### ISSUE THREAD

**Issue by 9aoyang** [Tencent/tmagic-editor#537]
<img width="1460" alt="image" src="https://github.com/Tencent/tmagic-editor/assets/17688032/87c19996-a87c-4102-9459-25c209aab211">
我想通过数据源的方式传一个数组到自定义的组件，不过看起来目前数据源只支持通过`data-source-input`配置 string 类型的数据， 是否支持其他类型？

**Comment by lmf** [comment]
找到支持的办法了吗？

**Comment by jia000** [comment]
使用data-source-field-select或者data-source-select
