### ISSUE TITLE
main.ts引入问题 一个略微低级的问题，大哥们有时间帮我看下

### ISSUE THREAD

**Issue by xutian111** [Tencent/tmagic-editor#538]
![image](https://github.com/Tencent/tmagic-editor/assets/89231915/1bfd7950-f3cc-42ff-b744-51093d412ad8)

![image](https://github.com/Tencent/tmagic-editor/assets/89231915/86bc3f31-c901-4b47-a280-cfed88fd14d4)
![image](https://github.com/Tencent/tmagic-editor/assets/89231915/ded5980c-d2d6-4421-ba1c-5cde0753270b)
为什么会这个样子啊
我用的是vue3+vite+pnpm
pnpm :8.2.0
node:16.18.1
npm :9.8.1

**Comment by jia000** [comment]
vite.config中加入`optimizeDeps: {
    esbuildOptions: {
      define: {
        global: 'globalThis',
      },
    },
  },`

**Comment by jia000** [comment]
使用的npm版本是多少？可以试试最新的beta版本
