### ISSUE TITLE
In the package.json of each package of packages, There is no export declaration file in the exports field

### ISSUE THREAD

**Issue by li-quan-wang** [Tencent/tmagic-editor#541]
**Describe the bug**
In a project that uses ts, the downloaded package is referenced in the project, and ts reports an error: the declaration file for the module "@tmagic/editor" cannot be found.

**To Reproduce**
Such as: import MagicEditor from '@tmagic/editor'

**Expected behavior**
In the package.json of each package of packages, add "types" to the exports field: "./types/index.d.ts"

**Screenshots**
The editor that reported the error: 
![image](https://github.com/Tencent/tmagic-editor/assets/43032049/470b5c26-4d03-4068-afe2-a2391efe6d1c)
Expected behavior:
![image](https://github.com/Tencent/tmagic-editor/assets/43032049/14ced198-0b5e-4527-a555-91e205130a15)
TS correlation:
![image](https://github.com/Tencent/tmagic-editor/assets/43032049/504a03e8-1277-4cad-9b93-314f36c7eb39)

**Desktop (please complete the following information):**
 - vue[3.3.4]
 - vite[4.4.5]
 - typescript[5.0.2]
 - node[16.20.0]

**Additional context**
typesctipt related documents：
(https://www.typescriptlang.org/docs/handbook/modules/reference.html#packagejson-exports)

**Comment by jia000** [comment]
https://github.com/Tencent/tmagic-editor/commit/8d8c8df82fd4f47ee2789c2322b948540c87c937
