### ISSUE TITLE
page_A页面和page_B页面，如何通过配置事件进行页面跳转？

### ISSUE THREAD

**Issue by turtleSpirit** [Tencent/tmagic-editor#545]
现在有两个页面page_A和page_B，然后page_A页面中有一个按钮，绑定事件点击跳转到page_B页面；这个功能可以怎么实现呢？

**Comment by jia000** [comment]
新增一个代码块，里面去实现跳转，page_A配置点击事件触发代码块

**Comment by turtleSpirit** [comment]
只能是通过window.location.href改变参数page的值的方式去跳转么？

**Comment by jia000** [comment]
可以看看playground的runtime是怎么切换页面的，目前page runtime并不支持除了改变url的其他方式切换页面

**Comment by jia000** [comment]
https://github.com/Tencent/tmagic-editor/issues/503
