### ISSUE TITLE
当我删除prop.model.object 其中一个键时数据未发生改变

### ISSUE THREAD

**Issue by CaspianSun** [Tencent/tmagic-editor#550]
![CleanShot 2023-11-08 at 16 29 46@2x](https://github.com/Tencent/tmagic-editor/assets/74301510/3c3c5cc7-c818-4226-a8d3-547be11260cf)

![CleanShot 2023-11-08 at 16 29 37@2x](https://github.com/Tencent/tmagic-editor/assets/74301510/7fab083d-a975-43c7-b08f-8e74aaf2d5eb)

**Comment by CaspianSun** [comment]
是设计成这样的么

**Comment by jia000** [comment]
修改config中的一个key值是不会触发vue自动更新的，需要整个config是一个新对象才行

**Comment by jia000** [comment]
这是vue的机制，并不是tmagic故意设计的

**Comment by CaspianSun** [comment]
> 修改config中的一个key值是不会触发vue自动更新的，需要整个config是一个新对象才行

我想我应该改掉的是完整的对象，在我触发emit('change' )后，我去追踪了数据（如图），可以看到我传递的config.style是没有color:“#000”的,当他调用完下面的函数返回的newNodes中多出了这个键 ， 这个 color:“#000” 在一开始是在对象中不存在的，我先进行了添加，添加成功了，在我删除的时候，就不行了。在我添加后，进行撤回，对象也未发生改变
同时我发现另一个issues #465 他遇到的问题跟我的应该是一样的

**Comment by jia000** [comment]
我看错了，我以为你是添加一个key

是无法删除key的，因为update的时候会merge(oldConfig, newConfig)。这里可以将对应key设置成空字符（不能是undefinded）

**Comment by jia000** [comment]
可以在保存的时候遍历一下所以key，将空字符的key删掉

**Comment by CaspianSun** [comment]
> 我看错了，我以为你是添加一个key
> 
> 是无法删除key的，因为update的时候会merge(oldConfig, newConfig)。这里可以将对应key设置成空字符（不能是undefinded）

为什么要去merge(oldConfig, newConfig) 数据,有什么必须这么做的原因吗,我不太理解为什么要这么设计

**Comment by jia000** [comment]
因为无法保证update的newConfig是完整的配置，如果组件定义的formConfig没有包含initValue里的所有自动就可能会导致数据丢失，除了initValue，还有像id，type，name这些系统字段也可能在formConfig里没有

**Comment by CaspianSun** [comment]
> 因为无法保证update的newConfig是完整的配置，如果组件定义的formConfig没有包含initValue里的所有自动就可能会导致数据丢失，除了initValue，还有像id，type，name这些系统字段也可能在formConfig里没有

那应该只需要在初始的时候执行一遍,后续的更新应该就不需要了吧,代码都是开发者写的,删掉什么不该删的也是开发者的问题

**Comment by jia000** [comment]
触发update不仅仅只有在右侧属性表单配置，还有在画布上的拖动，粘贴等等，甚至还有业务扩展上直接调用update api，这些情况大部分都不会传入完整的配置，如果不统一做merge，就需要在各个地方做

**Comment by CaspianSun** [comment]
好的,明白了
