### ISSUE TITLE
编辑区拖动组件顶部三个点位，实现放大缩小时位置错乱

### ISSUE THREAD

**Issue by starGodXy** [Tencent/tmagic-editor#559]
如题，如图
![微信截图_20231213180022](https://github.com/Tencent/tmagic-editor/assets/100547516/01736fd1-a0f3-407e-875b-8fe2db2d9978)
。具体可以看官网文档中的playground。

**Comment by jia000** [comment]
组件放大缩小，还是画布放大缩小？

**Comment by 1764734364** [comment]
放大缩小都会出现

**Comment by 1764734364** [comment]
组件放大缩小

**Comment by pi-de-bu-tan** [comment]
感觉是这里的问题., 'marginToppx' 这个是不是笔误

<img width="824" alt="1" src="https://github.com/Tencent/tmagic-editor/assets/33285114/bda669f6-793e-4af1-942c-94d266f92e1c">

**Comment by pi-de-bu-tan** [comment]
@jia000

**Comment by yigaywoligiaogiao** [comment]
遇到相同的问题了 过来一看issue还真有
