### ISSUE TITLE
form中的table使用page-fragment-select进行选择时,runtime的props中的config不会改变

### ISSUE THREAD

**Issue by CaspianSun** [Tencent/tmagic-editor#568]
![CleanShot 2024-01-17 at 15 42 54@2x](https://github.com/Tencent/tmagic-editor/assets/74301510/a216c29c-48c0-474f-8c16-0d5ecfe280e3)
普通的改变不会触发更新,删除可以
![CleanShot 2024-01-17 at 15 43 03@2x](https://github.com/Tencent/tmagic-editor/assets/74301510/71e9f01d-a5c4-43b0-ae0b-7e5972ffdff4)
展开配置后进行选择,可以触发
@jia000

**Comment by khuntoriia** [comment]
没太看懂问题是什么，能详细描述下你的问题吗，是说page-fragment-select选完之后，页面内的page-fragment-container组件渲染内容没生效？

**Comment by CaspianSun** [comment]
> 没太看懂问题是什么，能详细描述下你的问题吗，是说page-fragment-select选完之后，页面内的page-fragment-container组件渲染内容没生效？

是的

**Comment by CaspianSun** [comment]
> 没太看懂问题是什么，能详细描述下你的问题吗，是说page-fragment-select选完之后，页面内的page-fragment-container组件渲染内容没生效？

我写了一个组件根据table选择的页面片去进行渲染,
![CleanShot 2024-01-18 at 08 54 01@2x](https://github.com/Tencent/tmagic-editor/assets/74301510/298031c0-3e30-4c83-8ab2-ab264ee36006)
![CleanShot 2024-01-18 at 08 54 16@2x](https://github.com/Tencent/tmagic-editor/assets/74301510/eaad3a2c-77d5-4776-bf4e-a6ad3d61cae8)
---
### 如上面两图所示,我将第一项的页面片切换成了第二页,视图并未发生改变
### 下图是我使用[展开配置]()中的选择框选择对应的页面片所展现出来的效果
---
![CleanShot 2024-01-18 at 08 55 08@2x](https://github.com/Tencent/tmagic-editor/assets/74301510/1da88c09-94a7-499c-8a44-a477d4f709c3)

**Comment by khuntoriia** [comment]
自己写的组件需要抛出change事件，参考https://github.com/Tencent/tmagic-editor/blob/30929e8bd313bfdb9e3492faf362dd60ce82435f/packages/editor/src/fields/PageFragmentSelect.vue#L57C3-L57C43

**Comment by khuntoriia** [comment]
<img width="342" alt="image" src="https://github.com/Tencent/tmagic-editor/assets/9763592/ec06d75d-0560-4347-a32d-65632d5ec3e2">
这个表单是通过tmgaic form schema写的还是你自己单独封装了组件，如果是自己写的组件需要向外抛出change事件，参考https://github.com/Tencent/tmagic-editor/blob/30929e8bd313bfdb9e3492faf362dd60ce82435f/packages/editor/src/fields/PageFragmentSelect.vue#L57C3-L57C43

正常的「展开配置」是什么？

**Comment by CaspianSun** [comment]
> <img alt="image" width="342" src="https://private-user-images.githubusercontent.com/9763592/297584892-ec06d75d-0560-4347-a32d-65632d5ec3e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NTM3MjcsIm5iZiI6MTcwNTU1MzQyNywicGF0aCI6Ii85NzYzNTkyLzI5NzU4NDg5Mi1lYzA2ZDc1ZC0wNTYwLTQzNDctYTMyZC02NTYzMmQ1ZWMzZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMThUMDQ1MDI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzNlNDAzNzZmMTMzZjQ4NzNkN2Q3MDM1ODNjYmQ5NTdjOTc2MTg5YWJmMTg5ZWM4YWFmZmFiODNmMGIyOGI4MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nhdtNeyYsD2H6-tu3hJC8EWQLTZ315oUm-v5rh9OoKo"> 这个表单是通过tmgaic form schema写的还是你自己单独封装了组件，如果是自己写的组件需要向外抛出change事件，参考https://github.com/Tencent/tmagic-editor/blob/30929e8bd313bfdb9e3492faf362dd60ce82435f/packages/editor/src/fields/PageFragmentSelect.vue#L57C3-L57C43
> 正常的「展开配置」是什么？

![CleanShot 2024-01-18 at 12 52 04@2x](https://github.com/Tencent/tmagic-editor/assets/74301510/ead61d83-395d-4466-b204-fde40d5a76b8)
tmgaic form schema写的,
就是你们这个table的展开配置功能啊
[table](https://tencent.github.io/tmagic-editor/docs/form-config/layout.html#table)
![CleanShot 2024-01-18 at 12 54 31@2x](https://github.com/Tencent/tmagic-editor/assets/74301510/157b93bb-2ee6-409a-a88a-1a1eb4eaec24)
展开配置后还有个下拉框,我去下拉那个下拉框数据是发生改变的,我去下拉默认的下拉框,数据不会发生改变

就是一个你们这个tmgaic form schema改变了数据,没有将更新传递到的runtime的问题

**Comment by CaspianSun** [comment]
> <img alt="image" width="342" src="https://private-user-images.githubusercontent.com/9763592/297584892-ec06d75d-0560-4347-a32d-65632d5ec3e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NTM3MjcsIm5iZiI6MTcwNTU1MzQyNywicGF0aCI6Ii85NzYzNTkyLzI5NzU4NDg5Mi1lYzA2ZDc1ZC0wNTYwLTQzNDctYTMyZC02NTYzMmQ1ZWMzZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMThUMDQ1MDI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzNlNDAzNzZmMTMzZjQ4NzNkN2Q3MDM1ODNjYmQ5NTdjOTc2MTg5YWJmMTg5ZWM4YWFmZmFiODNmMGIyOGI4MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nhdtNeyYsD2H6-tu3hJC8EWQLTZ315oUm-v5rh9OoKo"> 这个表单是通过tmgaic form schema写的还是你自己单独封装了组件，如果是自己写的组件需要向外抛出change事件，参考https://github.com/Tencent/tmagic-editor/blob/30929e8bd313bfdb9e3492faf362dd60ce82435f/packages/editor/src/fields/PageFragmentSelect.vue#L57C3-L57C43
> 正常的「展开配置」是什么？
# 请看**VCR**
https://github.com/Tencent/tmagic-editor/assets/74301510/f521e42f-edc1-423b-8c1e-07574f95c8bd

**Comment by jia000** [comment]
需要看你的swiper组件是怎么实现的，我这里简单的模拟了一个组件，是符合预期的
```html
<template>
  <div :id="`${config.id || ''}`" :style="style">
    <PageFragmentContainer v-for="item in config.fragments" :key="item.id" :config="item"></PageFragmentContainer>
  </div>
</template>

<script lang="ts" setup>
import { computed, inject } from 'vue';

import Core from '@tmagic/core';
import PageFragmentContainer from '@tmagic/ui/src/page-fragment-container/src/PageFragmentContainer.vue';
import useApp from '@tmagic/ui/src/useApp';

const props = withDefaults(
  defineProps<{
    config: any;
    model?: any;
  }>(),
  {
    model: () => ({}),
  },
);

const app: Core | undefined = inject('app');

const style = computed(() => app?.transformStyle(props.config.style || {}));

useApp({
  config: props.config,
});
</script>
```

```js

export default [
  {
    name: 'fragments',
    type: 'table',
    items: [
      {
        type: 'page-fragment-select',
        name: 'pageFragmentId',
        label: '页面片',
      },
    ],
  },
];

```

**Comment by CaspianSun** [comment]
> ```js
> export default [
>   {
>     name: 'fragments',
>     type: 'table',
>     items: [
>       {
>         type: 'page-fragment-select',
>         name: 'pageFragmentId',
>         label: '页面片',
>       },
>     ],
>   },
> ];
> ```

export default [
  {
    name: 'current',
    type: 'data-source-input',
    text: '激活索引'
  },
  {
    type: 'table',
    name: 'fragments',
    items: [
      {
        type: 'page-fragment-select',
        name: 'id',
        label: 'Swiper页面片'
      }
    ]
  }
]


测试了一下发现用id当作键时出现我所提及到的情况

**Comment by jia000** [comment]
是使用PageFragmentContainer组件来渲染的吗？PageFragmentContainer要求使用的pageFragmentId

**Comment by CaspianSun** [comment]
﻿﻿﻿发自我的 iPhone发自我的 iPhone在 2024年1月19日，16:26，roymondchen ***@***.***> 写道：﻿
是使用PageFragmentContainer组件来渲染的吗？PageFragmentContainer要求使用的pageFragmentId

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
是的table中的key是id 我在swiper中修改了传递到PageFragmentContainer的config并把id赋值到pageFragmentId

**Comment by CaspianSun** [comment]
> 是使用PageFragmentContainer组件来渲染的吗？PageFragmentContainer要求使用的pageFragmentId

```js
export default [
  {
    type: 'table',
    name: 'fragments',
    items: [
      {
        type: 'page-fragment-select',
        name: 'id',
        label: 'Swiper页面片'
      }
    ]
  }
]
```

```vue
<template>
  <div :id="`${config.id || ''}`" :style="style">
    <PageFragmentContainer
      v-for="(item, index) in config.fragments"
      :key="index"
      :config="{
        pageFragmentId: item.id
      }"
    ></PageFragmentContainer>
  </div>
</template>

<script lang="ts" setup>
import { computed, inject } from 'vue'
import Core from '@tmagic/core'
// import PageFragmentContainer from '@tmagic/ui/src/page-fragment-container/src/PageFragmentContainer.vue'
// import useApp from '@tmagic/ui/src/useApp'

import useApp from '@ui/utils/useApp'
import PageFragmentContainer from '@ui/pageFragmentContainer'

const props = withDefaults(
  defineProps<{
    config: any
    model?: any
  }>(),
  {
    model: () => ({})
  }
)

const app: Core | undefined = inject('app')

const style = computed(() => app?.transformStyle(props.config.style || {}))

useApp({
  config: props.config
})
</script>
```
---

## 如果我将id改为id1或其他就正常了
```js
export default [
  {
    type: 'table',
    name: 'fragments',
    items: [
      {
        type: 'page-fragment-select',
        name: 'id1',
        label: 'Swiper页面片'
      }
    ]
  }
]
```

```vue
<template>
  <div :id="`${config.id || ''}`" :style="style">
    <PageFragmentContainer
      v-for="(item, index) in config.fragments"
      :key="index"
      :config="{
        pageFragmentId: item.id1
      }"
    ></PageFragmentContainer>
  </div>
</template>

<script lang="ts" setup>
import { computed, inject } from 'vue'
import Core from '@tmagic/core'
// import PageFragmentContainer from '@tmagic/ui/src/page-fragment-container/src/PageFragmentContainer.vue'
// import useApp from '@tmagic/ui/src/useApp'

import useApp from '@ui/utils/useApp'
import PageFragmentContainer from '@ui/pageFragmentContainer'

const props = withDefaults(
  defineProps<{
    config: any
    model?: any
  }>(),
  {
    model: () => ({})
  }
)

const app: Core | undefined = inject('app')

const style = computed(() => app?.transformStyle(props.config.style || {}))

useApp({
  config: props.config
})
</script>
```

**Comment by jia000** [comment]
id默认会作为[element-plus row-key](https://element-plus.org/zh-CN/component/table.html#table-%E5%B1%9E%E6%80%A7)传入，当其发生变化时会导致table重新渲染，猜测是这个原因。可以试试使用[rowKey](https://github.com/Tencent/tmagic-editor/blob/fbb5b3c9474fadc8f88143ba2070dbc9364eaea7/packages/form/src/schema.ts#L672)重新指定[element-plus row-key](https://element-plus.org/zh-CN/component/table.html#table-%E5%B1%9E%E6%80%A7)的值

**Comment by CaspianSun** [comment]
这是@tmagic/form table的问题
