### ISSUE TITLE
关于自定义组件的导入问题

### ISSUE THREAD

**Issue by jacksion1234** [Tencent/tmagic-editor#571]
问题描述：
按照官网的文档，我在tmagic-editor这个项目中创建了自定义组件，并且也实现了引入，但是想要在tmagic-admin这个项目中使用，每次都得打包tmagic-editor一次，然后放入到tmagic-admin项目中。

期望：
目前能实现在tmagic-admin项目中直接创建自定义组件，然后被编辑器识别吗？我试过创建全局组件"magic-ui-XXX"这种的，倒是可以添加到自定义组件中，但是这种方式创建的自定义组件的config和value这些属性怎么导入我就不明白了。

**Comment by jacksion1234** [comment]
说错了，创建全局组件"magic-ui-XXX"这种的应该也是不行的，识别不到。

**Comment by jia000** [comment]
config是通过[propsconfigs](https://tencent.github.io/tmagic-editor/docs/api/editor/props.html#propsconfigs)

**Comment by jacksion1234** [comment]
按照您说的，propsconfigs和propsvalues确实可以配置，右侧表单也可以显示，但是我上面说的"magic-ui-XXX"这种全局组件并不能与自定义的组件绑定，比如自定义组件类型为magiccube，我在tmagic-admin项目中全局注册了magic-ui-magiccube这个组件，点击左侧组件栏添加该组件，只会出现一个空白的框，并非是magic-ui-magiccube这个组件，是还需要什么嘛？

**Comment by jia000** [comment]
要在runtime [tmagic.config](https://github.com/Tencent/tmagic-editor/blob/fbb5b3c9474fadc8f88143ba2070dbc9364eaea7/runtime/vue3/tmagic.config.ts#L6)中的packages配置上

**Comment by jacksion1234** [comment]
嗯，这个我知道，但是目前每次都得在tmagic-editor这边调试好组件，然后打包runtime到正式项目里去，有的时候俩边环境也不一样，可能还得单独调一下，有点麻烦，所以想着能不能不动这个runtime，然后直接在正式项目中建组件就能够被编辑器识别。

**Comment by jia000** [comment]
你可以把[magicApp](https://github.com/Tencent/tmagic-editor/blob/7db8d8f45f232131259b1c407239088475fac76f/runtime/vue3/page/main.ts#L39)放到window上，然后把组件单独打包，然后加载注册

```ts
// const components = await import(xxxxx)
Object.entries(components).forEach(([type, component]: [string, any]) => {
  magicApp.component(`magic-ui-${type}`, defineAsyncComponent(component));
});
```
