### ISSUE TITLE
开发一个新组件，在新组件内部需要修改formConfig的某个属性，这个是使用什么方法可以完成

### ISSUE THREAD

**Issue by kingjinkin** [Tencent/tmagic-editor#578]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jia000** [comment]
具体描述一下场景，要实现什么功能，在什么时机需要改？

**Comment by jia000** [comment]
https://github.com/Tencent/tmagic-editor/issues/567

**Comment by kingjinkin** [comment]
我想开发一个文本编辑器组件，该组件可以双击就可以编辑，该组件获取到的文本字符串怎么传递到该组件的form表单中

**Comment by jia000** [comment]
调用editorService.update把数据更新就可以了，更新的数据要包含id
```js
editorService.update({ id: xxx, text: xxx })
```

**Comment by Little-LittleProgrammer** [comment]
> 请问组件内部如何获取到editorService呢？看了下示例，有注入app，但是没有各类service的注入
如果是ui组件的话, 内部是无法调用service, service是编辑器专属的, runtime无法使用, 否则最终的h5页面会有很多的冗余代码
应该是这样的😀

**Comment by microNewLife** [comment]
> > 请问组件内部如何获取到editorService呢？看了下示例，有注入app，但是没有各类service的注入
> 
> 如果是ui组件的话, 内部是无法调用service, service是编辑器专属的, runtime无法使用, 否则最终的h5页面会有很多的冗余代码 应该是这样的😀

明白了，那我组件内如何修改对应props.config对象的某个值呢？比如props.config.foo,右侧表单输入的是‘bar’,组件内部想修改成'ugly'，找了很久的文档都没找到，看代码也没有看到。这个需求有办法解决吗？

**Comment by jia000** [comment]
> > > 请问组件内部如何获取到editorService呢？看了下示例，有注入app，但是没有各类service的注入
> > 
> > 
> > 如果是ui组件的话, 内部是无法调用service, service是编辑器专属的, runtime无法使用, 否则最终的h5页面会有很多的冗余代码 应该是这样的😀
> 
> 明白了，那我组件内如何修改对应props.config对象的某个值呢？比如props.config.foo,右侧表单输入的是‘bar’,组件内部想修改成'ugly'，找了很久的文档都没找到，看代码也没有看到。这个需求有办法解决吗？

组件内是不允许修改config的
