### ISSUE TITLE
tmagic-server 目录下缺少 pm2.config.js

### ISSUE THREAD

**Issue by ibmsoft** [Tencent/tmagic-editor#58]
缺少 pm2.config.js

**Comment by GreenMashimaro** [comment]
I have the same problem.

run `magic-admin/setup.sh` prompt `[PM2][ERROR] File pm2.config.js not found`
https://github.com/Tencent/tmagic-editor/blob/master/magic-admin/setup.sh#L37

Can you help fix it?
