### ISSUE TITLE
开发一个文本编辑组件，怎么接收到双击事件进入文本编辑状态，而且在这个编辑状态可以相应鼠标选中文本，定位光标操作

### ISSUE THREAD

**Issue by kingjinkin** [Tencent/tmagic-editor#580]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jia000** [comment]
双击事件已经有对应的行为了
![image](https://github.com/Tencent/tmagic-editor/assets/4327396/4429f94b-733a-46c1-9335-05db6e1c5db3)
可以通过修改其行为实现

**Comment by kingjinkin** [comment]
![GIF 2024-3-22 21-51-43](https://github.com/Tencent/tmagic-editor/assets/6133533/fce20434-e902-4323-bd08-42b0763c01f0)

您的方法是否可以实现组件的编辑功能

**Comment by kingjinkin** [comment]
大佬，请问组件怎么可以收到鼠标相关事件呢
