### ISSUE TITLE
组件内部通过api获取到某些数据，如何用这些数据去反向修改右侧编辑框中的数据呢？

### ISSUE THREAD

**Issue by microNewLife** [Tencent/tmagic-editor#595]
如题，之前查找issue，并没遭到类似的答案，现在是可以通过editor来修改，那在组件中 如何修改这些数据呢？

**Comment by jia000** [comment]
无法做到，也不建议这样做，是什么场景需要这样？

**Comment by microNewLife** [comment]
那是否是我使用上有错误呢？比如组件中展示某些数据，可以从api中获取也可以手动编辑；当从api获取的时候，需要同步修改编辑框中对应的数据，以免组件展示的数据与编辑框中的数据不一致。

**Comment by jia000** [comment]
应该在formConfig中配置一个select，这个select可以是remote模式，通过api获取下拉列表，然后用户配置的时候选择列表中的某一项后，在onChange中取设置其他配置数据
