### ISSUE TITLE
input组件无法及时更新数据。

### ISSUE THREAD

**Issue by 907043175** [Tencent/tmagic-editor#599]
1、通过api方式（请求后台api）获取文本数据。
2、获取的文本，设置到input组件。
3、input组件，无法显示获取的文本数据

这个bug比较着急，烦请帮忙看看。

**Comment by jia000** [comment]
请提供一个示例，是如果设置到input组件的

**Comment by 907043175** [comment]
技术已经解决了。谢谢关注这个问题。
