### ISSUE TITLE
chrome91版本，调用 editorService.update() 会出错，是否可以在下个版本兼容一下

### ISSUE THREAD

**Issue by li-quan-wang** [Tencent/tmagic-editor#606]
浏览器版本：chrome91

问题：调用 editorService.update() 会出错，因为 Object.hasOwn 方法在该版本不支持，是否可以做下兼容

截图如下：
![image](https://github.com/Tencent/tmagic-editor/assets/43032049/d9b2fc15-9698-40e0-b685-45e60aa26b86)
![image](https://github.com/Tencent/tmagic-editor/assets/43032049/27d9642e-b6f4-4a85-af33-fa72ec8ce2a9)

**Comment by li-quan-wang** [comment]
我尝试过了，使用legacy插件应该只是提高自身项目的兼容性吧。而 doUpdate 方法在我使用的 @tmagic/editor 的包里，应该不起作用吧。

**Comment by jia000** [comment]
legacy 是加在你使用 @tmagic/editor的项目上的，怎么会不起作用
