### ISSUE TITLE
右侧样式面板设置字体不生效

### ISSUE THREAD

**Issue by Zzzzzhoukekkk** [Tencent/tmagic-editor#609]
自定义右侧样式面板内容
设置字体后不生效
`{
                type: 'data-source-field-select',
                name: 'fontFamily',
                text: '字体',
                checkStrictly: false,
                dataSourceFieldType: ['string'],
                fieldConfig: {
                  type: 'select',
                  options: [
                    { text: 'FZHuoLTJW_Da', value: 'FZHuoLTJW_Da' },
                  ],
                },
              },`

**Comment by jia000** [comment]
FZHuoLTJW_Da这个字体不是系统自带的吧？自定义字体需要在runtime中使用@font-face引入字体文件

**Comment by Zzzzzhoukekkk** [comment]
支持@font-face引入字体链接

**Comment by Zzzzzhoukekkk** [comment]
支持@font-face引入字体链接嘛
需要在runtime的哪里引入呀
在playground和runtime都引入了但只有部分生效

**Comment by Zzzzzhoukekkk** [comment]
生效喽，嘿嘿，感谢感谢
