### ISSUE TITLE
数据源 数组字段绑定 页面卡死

### ISSUE THREAD

**Issue by GoToBoy** [Tencent/tmagic-editor#611]
![4b5468d4c62930484bf0ac0f73ddc265](https://github.com/Tencent/tmagic-editor/assets/2384105/4c74c3a5-c9f3-4351-a97d-69f78b875988)
绑定数组时候, 
1. 提示错了,没有给数组序号的下拉选项
2. s输入 xxds.array[0].   在. 后页面卡死

![37c4d1d29f2aae9a69dcd83367e80655](https://github.com/Tencent/tmagic-editor/assets/2384105/86cdc180-7a00-4e5e-a8b8-a4ec7c094320)

**Comment by GoToBoy** [comment]
<img width="611" alt="image" src="https://github.com/Tencent/tmagic-editor/assets/2384105/23cb513a-1aa3-4d45-87fc-48506ec97776">
卡死在while循环里了

**Comment by GoToBoy** [comment]
1. 页面卡死是 break的问题
2. 数组数据源怎么引用，试了下 ${id.array.0.a} 和${id.array[0].a} 都无法使用

**Comment by jia000** [comment]
数组数据源一般是要搭配迭代器容器使用
