### ISSUE TITLE
页面、页面片还有底下索引tab有什么作用呢？

### ISSUE THREAD

**Issue by rancho-xjq** [Tencent/tmagic-editor#620]
![image](https://github.com/Tencent/tmagic-editor/assets/55220313/b78e42b5-4314-45d7-ba7d-6133a5fbe979)
页面、页面片还有底下索引tab有什么作用呢？
文档里面没看到有对应介绍
谢谢解答

**Comment by jia000** [comment]
tab可以切换页面，页面片可以被不同的页面共享

**Comment by LeftProgrammer** [comment]
这种多页面在独立部署后，其他页面是怎么访问啊？

**Comment by LeftProgrammer** [comment]
@jia000

**Comment by jia000** [comment]
独立部署后不是每个页面都有独立的url吗？可以详细描述一下吗？

**Comment by jia000** [comment]
在url中通过page参数指定页面id来访问
