### ISSUE TITLE
sidebar组件下的的折叠面板是否可以多级

### ISSUE THREAD

**Issue by xx-painter05** [Tencent/tmagic-editor#621]
目前sidebar的折叠面板只支持一级
![image](https://github.com/user-attachments/assets/045ceca2-b6d4-40d7-8dbf-a1a10b6ce19b)
是否考虑过根据**componentGroupList**传入的结构做成多级展示呢
或者是否可以直接暴露一个**comoonent-list**插槽呢 因为目前只有单个**component-list-item** 插槽

**Comment by jia000** [comment]
v1.4.15版本新增comoonent-list插槽
