### ISSUE TITLE
magic-admin 启动后页面编辑出现错误

### ISSUE THREAD

**Issue by wrr008123** [Tencent/tmagic-editor#69]
使用 setup.sh 运行的项目，但是在编辑页面出现错误！

希望能够再详细说一下项目中runtimeUrl的配置

![image](https://user-images.githubusercontent.com/34823541/168271402-c299bebe-4cd4-454e-9eeb-ff9fa1d2340f.png)

**Comment by khuntoriia** [comment]
关于runtime可以看看文档这里的介绍  https://tencent.github.io/tmagic-editor/docs/page/introduction.html#runtime
图中报错config.js是在magic-admin/web/src/views/editor.vue使用的，由playground打包生成不要手动修改

为了便于管理端demo的启动，已经将runtime打包产物上传至git，请更新代码再试试
#73
