### ISSUE TITLE
启动magic-admin新建活动报错

### ISSUE THREAD

**Issue by xuyaxiong** [Tencent/tmagic-editor#71]
错误消息：Field 'act_crypto_id' doesn't have a default value

**Comment by khuntoriia** [comment]
请问是否有创建对应库表？参考文档：
<img width="775" alt="image" src="https://user-images.githubusercontent.com/9763592/168587556-9f52d770-c9e5-493a-b10c-c9cd995862b7.png">

**Comment by unique-vv** [comment]
mysql> show tables
    -> ;
+--------------------------+
| Tables_in_magic-admin-db |
+--------------------------+
| magic_act_info           |
| magic_ui_config          |
+--------------------------+
2 rows in set (0.00 sec)

创建了   还是报错

**Comment by khuntoriia** [comment]
请确认加密秘钥是否配置在了 key.ts中，如还有问题，请提供详细的错误信息

**Comment by haixin-fang** [comment]
我也报该错误

**Comment by haixin-fang** [comment]
@unique-vv @xuyaxiong 老哥,解决了没
