### ISSUE TITLE
自定义组件-疑问

### ISSUE THREAD

**Issue by wrr008123** [Tencent/tmagic-editor#75]
再次打扰，抱歉

我想在自定义组件中使用其他UI库，如将ElementPlus中的Image组件包装为自定义组件

那我应该怎样做才能保证其elementPlus的ui能够正确渲染呢？

我试过在组件中引入了elementplus、在runtime中引入、在主体项目中引用，都无法正确渲染，希望能得到解答，谢谢！

![6$WW%1W_G_BT_E{~37J4769](https://user-images.githubusercontent.com/34823541/168765319-0ec1cc1d-e9ca-4902-8909-615872b8eb3c.jpg)

![(W3W}L0I7YD3JBZDC 32$CN](https://user-images.githubusercontent.com/34823541/168765358-75f88768-9972-4187-97c3-942e4b24cba0.jpg)

**Comment by jia000** [comment]
runtime哪里引入element-plus？将路径，代码贴出来看看

**Comment by wrr008123** [comment]
感谢你的回复，让我确定了是在runtime中引入，这很重要！

我之前添加elementPlus是手动写在comp-entry.ts -> plugins 中的

刚刚准备去截图发现之前引入的不见了，发现这个类在build过程中会被重新写入

所以我又选择在playground目录下的main.ts中试了一次，这次成功了！

**Comment by jia000** [comment]
建议不要全局注册，而是在组件内使用components配置

**Comment by wrr008123** [comment]
好的，谢谢你的建议！

顺带提一下，由于runtime打包后playground.html、page.html中路径为/tmagic-editor/xx/runtime/.....

因此将runtime内容直接放到tmagic-admin -> web -> public -> /runtime/vue3 目录下时，导致最终目录为 public/runtime/vue3/playground.html

那后续将会找不到playground.html中引入的这些js与css文件

希望简单修改一下，不然会导致许多同学无法直接将项目跑起来，同时也减少相关问题的疑问

![image](https://user-images.githubusercontent.com/34823541/168773358-ef04ce45-d02c-40f6-bd5f-71caf46498ae.png)

**Comment by jia000** [comment]
runtime的产物是需要放到一个静态资源服务器，不一定是在tmagic-admin/web中，这里的web只是扮演了资源服务器（cdn）的身份。playground.html里的资源路径可以通过vite.config.js配置

**Comment by wrr008123** [comment]
好的，谢谢解答😘
