### ISSUE TITLE
管理端Demo，新建活动接口报错

### ISSUE THREAD

**Issue by zhongs** [Tencent/tmagic-editor#88]
![image](https://user-images.githubusercontent.com/12317641/170075134-f1035bb8-8c02-4564-ac64-722d00ee8539.png)

act_id 自增ID导致 Crypto.encode 方法报错

**Comment by khuntoriia** [comment]
请问传入Crypto.encode的actId是什么

**Comment by zhongs** [comment]
> 请问传入Crypto.encode的actId是什么

![image](https://user-images.githubusercontent.com/12317641/170219590-debb8d01-faef-43d3-9d95-0fc0b139467c.png)
找到问题了；这个 key 要设置一个length 等于32长度的字符串
